window.DADOS_INVENTARIO = [
    {
        "fase": "Ler primeiro",
        "fichamento": "02_fichamento_small_adrenal_glands.pdf",
        "cautelas": "Essencial para a visão sistêmica da Pandora. Artigo antigo, mas muito importante.",
        "codigo": "50",
        "grupo": "Síndrome de Pandora e eixo neuroendócrino",
        "tipoEstudo": "Estudo experimental comparativo, com teste de estimulação por ACTH, dosagem de cortisol, análise morfométrica e avaliação histológica das glândulas adrenais de gatos saudáveis e gatos com cistite intersticial felina.",
        "procedencia": "preenchida por voce na triagem",
        "porQueLer": "Estudo clássico que relaciona alterações adrenais, eixo hipotálamo hipófise adrenal e cistite intersticial felina.",
        "comoUsar": "Usar como base neuroendócrina para discutir estresse, eixo HHA, adrenal e resposta fisiológica na Síndrome de Pandora.",
        "arquivo": "PDF/Primeiras Leituras/02_SMALL ADRENAL GLANDS IN CATS WITH FELINE INTERSTITIAL.pdf",
        "referencia": "WESTROPP, Jodi L.; WELK, Kristin A.; BUFFINGTON, C. A. Tony. Small adrenal glands in cats with feline interstitial cystitis. The Journal of Urology, v. 170, n. 6 Pt 1, p. 2494–2497, 2003. DOI: 10.1097/01.ju.0000095566.63870.66.",
        "status": "fichamento incompleto — referência A CONFERIR",
        "ano": "2003",
        "titulo": "Small adrenal glands in cats with feline interstitial cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Artigo antigo; usar com revisões recentes.",
        "codigo": "43",
        "grupo": "Mudança de paradigma em FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Base conceitual para evolução histórica da compreensão da FIC.",
        "comoUsar": "Usar na introdução clínica/histórica.",
        "arquivo": "PDF/Relevantes/Changing Paradigms.pdf",
        "referencia": "KRUGER, John M.; OSBORNE, Carl A.; LULICH, Jody P. Changing Paradigms of Feline Idiopathic Cystitis. Veterinary Clinics of North America - Small Animal Practice, v. 39, n. 1, p. 15-40, 2009. DOI: 10.1016/j.cvsm.2008.09.008.",
        "status": "arquivo obtido",
        "ano": "2009",
        "titulo": "Changing Paradigms of Feline Idiopathic Cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Muito importante.",
        "codigo": "19",
        "grupo": "Síndrome de Pandora / além do trato urinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Essencial para sustentar que o problema ultrapassa a bexiga e envolve estresse/sistema.",
        "comoUsar": "Usar para a transição FIC → Síndrome de Pandora e ferramenta sistêmica.",
        "arquivo": "",
        "referencia": "BUFFINGTON, C. A. Tony. Idiopathic cystitis in domestic cats-beyond the lower urinary tract. Journal of Veterinary Internal Medicine, v. 25, n. 4, p. 784-796, 2011. DOI: 10.1111/j.1939-1676.2011.0732.x.",
        "status": "ainda nao obtido",
        "ano": "2011",
        "titulo": "Idiopathic cystitis in domestic cats-beyond the lower urinary tract",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Artigo antigo, mas específico.",
        "codigo": "34",
        "grupo": "Fatores de risco e apresentação clínica FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Fornece variáveis clínicas e fatores de risco para classificação/triagem.",
        "comoUsar": "Usar na definição de entradas clínicas e questionário.",
        "arquivo": "",
        "referencia": "DEFAUW, Pieter A. M. et al. Risk factors and clinical presentation of cats with feline idiopathic cystitis. Journal of Feline Medicine and Surgery, v. 13, n. 12, p. 967-975, 2011. DOI: 10.1016/j.jfms.2011.08.001.",
        "status": "ainda nao obtido",
        "ano": "2011",
        "titulo": "Risk factors and clinical presentation of cats with feline idiopathic cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Leitura obrigatória. Usar na introdução e justificativa.",
        "codigo": "51",
        "grupo": "Síndrome de Pandora e mudança conceitual",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Artigo central sobre a evolução conceitual de FUS e CIF para Síndrome de Pandora.",
        "comoUsar": "Usar como base conceitual principal para justificar que o foco da pesquisa deve ser Síndrome de Pandora, e não apenas cistite.",
        "arquivo": "PDF/Primordiais/tony-buffington-et-al-2014-from-fus-to-pandora-syndrome.pdf",
        "referencia": "NAO CONFIRMADO",
        "status": "fichamento concluido",
        "ano": "2014",
        "titulo": "From FUS to Pandora syndrome: Where are we, how did we get here, and where to now?",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Artigo mais antigo, não substituir revisões recentes.",
        "codigo": "40",
        "grupo": "Revisão clínica FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão clínica útil para alinhamento com o veterinário.",
        "comoUsar": "Usar como apoio clínico, especialmente para linguagem veterinária.",
        "arquivo": "PDF/Relevantes/Feline_idiopathic_cystitis_VCNA_2015.pdf",
        "referencia": "FORRESTER, S. Dru; TOWELL, Todd L. Feline Idiopathic Cystitis. Veterinary Clinics of North America - Small Animal Practice, v. 45, n. 4, p. 783-806, 2015. DOI: 10.1016/j.cvsm.2015.02.007.",
        "status": "arquivo obtido",
        "ano": "2015",
        "titulo": "Feline Idiopathic Cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "Cautela: sem DOI e com possível tradução/ano incorreto.",
        "codigo": "45",
        "grupo": "Base clínica histórica FIC/IC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "O tema é relevante, mas os metadados parecem inconsistentes e precisam conferência no Zotero.",
        "comoUsar": "Usar apenas se a referência estiver corretamente identificada.",
        "arquivo": "",
        "referencia": "CHEW, Dennis J; BUFFINGTON, Tony. Cistite intersticial felina. Journal of the American Veterinary Medical Association, 1999. Disponivel em: https://avmajournals.avma.org/view/journals/javma/215/5/javma.1999.215.05.682.pdf.",
        "status": "ainda nao obtido",
        "ano": "2016",
        "titulo": "Cistite intersticial felina",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Conferir metadados; título traduzido.",
        "codigo": "42",
        "grupo": "Inflamação/remodelação em IC felina",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Ajuda a explicar alterações teciduais na bexiga/uretra em cistite intersticial felina.",
        "comoUsar": "Usar para fisiopatologia e possíveis variáveis clínicas.",
        "arquivo": "",
        "referencia": "KULLMANN, F. Aura et al. Inflamação e remodelação tecidual na bexiga e uretra na cistite intersticial felina. Frontiers in Systems Neuroscience, v. 12, 2018. DOI: 10.3389/FNSYS.2018.00013/FULL.",
        "status": "ainda nao obtido",
        "ano": "2018",
        "titulo": "Inflamação e remodelação tecidual na bexiga e uretra na cistite intersticial felina.",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Diretriz clínica.",
        "codigo": "29",
        "grupo": "Diretriz ISCAID para ITU",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Importante para diferenciar infecção urinária bacteriana de FIC/Pandora.",
        "comoUsar": "Usar para critérios de exclusão, diagnóstico diferencial e segurança clínica.",
        "arquivo": "",
        "referencia": "WEESE, J. Scott et al. International Society for Companion Animal Infectious Diseases (ISCAID) guidelines for the diagnosis and management of bacterial urinary tract infections in dogs and cats. Veterinary Journal, v. 247, p. 8-25, 2019. DOI: 10.1016/j.tvjl.2019.02.008.",
        "status": "ainda nao obtido",
        "ano": "2019",
        "titulo": "International Society for Companion Animal Infectious Diseases (ISCAID) guidelines for the diagnosis and management of bacterial urinary tract infections in dogs and cats",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Artigo específico, mas não central de IA.",
        "codigo": "37",
        "grupo": "Biomarcador Flt3L em IC felina",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Traz biomarcador urinário associado à cistite intersticial felina.",
        "comoUsar": "Usar em biomarcadores e variáveis laboratoriais.",
        "arquivo": "",
        "referencia": "CREECH, Renea; BADRI, Dayakar; PANICKAR, Kiran. Flt3L, a Cytokine and Growth Factor, Is Reduced in the Urine of Felines With Interstitial Cystitis. Current Developments in Nutrition, v. 5, p. 1125, 2021. DOI: 10.1093/cdn/nzab061_009.",
        "status": "ainda nao obtido",
        "ano": "2021",
        "titulo": "Flt3L, a Cytokine and Growth Factor, Is Reduced in the Urine of Felines With Interstitial Cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Essencial.",
        "codigo": "17",
        "grupo": "Revisão FIC: risco, biomarcadores e manejo",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Artigo guarda-chuva para FIC: prevalência, fatores de risco, biomarcadores e manejo.",
        "comoUsar": "Usar como base clínica principal para o problema-alvo.",
        "arquivo": "PDF/Relevantes/Prevalence, Risk Factors,.pdf",
        "referencia": "HE, Chengxi et al. Prevalence, Risk Factors, Pathophysiology, Potential Biomarkers and Management of Feline Idiopathic Cystitis: An Update Review. Frontiers in Veterinary Science, v. 9, 2022. DOI: 10.3389/fvets.2022.900847.",
        "status": "arquivo obtido",
        "ano": "2022",
        "titulo": "Prevalence, Risk Factors, Pathophysiology, Potential Biomarkers and Management of Feline Idiopathic Cystitis: An Update Review",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Base clínica importante.",
        "codigo": "24",
        "grupo": "Microbioma urinário em FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Estudo relevante para interpretar microbioma urinário em gatos com FIC.",
        "comoUsar": "Usar para discutir exames, microbioma e diferenciação de causas infecciosas/não infecciosas.",
        "arquivo": "",
        "referencia": "BALBONI, Andrea et al. No viable bacterial communities reside in the urinary bladder of cats with feline idiopathic cystitis. Research in Veterinary Science, v. 168, 2024. DOI: 10.1016/j.rvsc.2024.105137.",
        "status": "ainda nao obtido",
        "ano": "2024",
        "titulo": "No viable bacterial communities reside in the urinary bladder of cats with feline idiopathic cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Contexto dos EUA. Ano vem do nome do arquivo, NAO CONFIRMADO no documento.",
        "codigo": "S9",
        "grupo": "Pratica clinica e conduta terapeutica",
        "tipoEstudo": "Survey",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Levantamento sobre como veterinarios nos EUA tratam FLUTD nao obstrutiva.",
        "comoUsar": "Mostra a distancia entre evidencia e pratica: util na justificativa de uma ferramenta de apoio.",
        "arquivo": "PDF_Para conhecimento/krause-et-al-2024-survey-of-veterinarians-in-the-usa-to-evaluate-trends-in-the-treatment-approach-for-non-obstructive.pdf",
        "referencia": "KRAUSE et al. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "2024",
        "titulo": "Survey of veterinarians in the USA to evaluate trends in the treatment approach for non-obstructive FLUTD",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Essencial.",
        "codigo": "15",
        "grupo": "Diretriz clínica FLUTD/FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Diretriz de consenso recente para diagnóstico e manejo de doenças do trato urinário inferior em gatos.",
        "comoUsar": "Usar como base normativa para o veterinário e critérios da ferramenta.",
        "arquivo": "",
        "referencia": "NAO CONFIRMADO",
        "status": "ainda nao obtido",
        "ano": "2025",
        "titulo": "iCatCare consensus guidelines on the diagnosis and management of lower urinary tract diseases in cats",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Verificar metadados, pois o título está traduzido.",
        "codigo": "26",
        "grupo": "Microbioma urinário e FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Conecta microbioma urinário, gatos saudáveis e FIC, útil para variáveis clínicas e discussão diagnóstica.",
        "comoUsar": "Usar em microbioma, exames complementares e limites da interpretação clínica.",
        "arquivo": "PDF/Characterization and comparative.pdf",
        "referencia": "THASSAKORN, P et al. Characterization and comparative analysis of urinary bacterial microbiome profiling in healthy cats and cats with feline idiopathic cystitis. Scientific Reports, 2026. DOI: 10.1038/s41598-025-34196-9.",
        "status": "arquivo obtido",
        "ano": "2026",
        "titulo": "Caracterização e análise comparativa do perfil do microbioma bacteriano urinário em gatos saudáveis e gatos com cistite idiopática felina.",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Não é artigo de IA.",
        "codigo": "41",
        "grupo": "Tratamento e manejo de FIC/IC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Estudo clínico recente sobre terapia alternativa em casos graves de cistite idiopática/intersticial em gatos machos.",
        "comoUsar": "Usar apenas na discussão de possibilidades terapêuticas e limites da ferramenta de apoio à decisão.",
        "arquivo": "",
        "referencia": "KENDALL, Allison et al. Low-dose radiation therapy for idiopathic or interstitial cystitis in male cats. Journal of veterinary internal medicine, v. 40, n. 1, 2026. DOI: 10.1093/jvimsj/aalaf029.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Low-dose radiation therapy for idiopathic or interstitial cystitis in male cats",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Artigo clínico, não IA.",
        "codigo": "27",
        "grupo": "Biomarcadores urinários e FLUTD",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Traz biomarcadores mensuráveis em urina/soro, úteis para pensar variáveis de entrada da ferramenta.",
        "comoUsar": "Usar em biomarcadores, classificação de risco e diferenciação entre FIC, urolitíase e obstrução.",
        "arquivo": "",
        "referencia": "MADEN, Mehmet et al. Serum and Urine Nerve Growth Factor and Glycosaminoglycan Levels in Obstructive and Non-Obstructive Feline Urolithiasis and Interstitial Cystitis. Veterinary Medicine and Science, v. 12, n. 3, 2026. DOI: 10.1002/vms3.70968.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Serum and Urine Nerve Growth Factor and Glycosaminoglycan Levels in Obstructive and Non-Obstructive Feline Urolithiasis and Interstitial Cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "LITERATURA CINZENTA. Titulo, instituicao e ano NAO CONFIRMADOS.",
        "codigo": "S10",
        "grupo": "Contexto e revisao",
        "tipoEstudo": "Dissertacao",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Material de apoio para contexto e vocabulario da area.",
        "comoUsar": "Apoio de leitura. Nao citar como fonte primaria.",
        "arquivo": "PDF_Para conhecimento/Mestrado-Medicina_Veterinaria-Julia_Aidos_Leal.pdf",
        "referencia": "LEAL, J. A. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Dissertacao de mestrado em Medicina Veterinaria (Julia Aidos Leal)",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Secao \"Reference Point\" (JAVMA). Ano, volume e paginacao NAO CONFIRMADOS.",
        "codigo": "S3",
        "grupo": "Risco de doenca, ambiente e fisiologia",
        "tipoEstudo": "Artigo de revisao/posicionamento",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Texto de Buffington que articula influencias externas e internas sobre o risco de adoecer.",
        "comoUsar": "Ponte conceitual entre ambiente e fisiologia, anterior a formulacao da Sindrome de Pandora.",
        "arquivo": "PDF/Primordiais/External and internal influences.pdf",
        "referencia": "BUFFINGTON, C. A. T. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "NAO CONFIRMADO",
        "titulo": "External and internal influences on disease risk in cats",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Ano e periodico NAO CONFIRMADOS. Verificar se cobre FIC especificamente.",
        "codigo": "S7",
        "grupo": "Biomarcadores lipidomicos em doenca felina",
        "tipoEstudo": "Revisao sistematica (PRISMA)",
        "procedencia": "parcial - autoria confirmada no PDF, resto NAO CONFIRMADO",
        "porQueLer": "Revisao sistematica guiada por PRISMA sobre assinaturas lipidomicas em doencas felinas.",
        "comoUsar": "Amplia o repertorio de biomarcadores alem dos urinarios ja no acervo.",
        "arquivo": "PDF/Lipidomic Signatures in Feline Disease A PRISMA-Guided.pdf",
        "referencia": "FONTES, A. C. et al. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo não localizado",
        "ano": "NAO CONFIRMADO",
        "titulo": "Lipidomic Signatures in Feline Disease: A PRISMA-Guided Systematic Review",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "LITERATURA CINZENTA. Resumo de evento, sem revisao por pares. Ano NAO CONFIRMADO.",
        "codigo": "S8",
        "grupo": "Prevencao da Sindrome de Pandora",
        "tipoEstudo": "Resumo de evento",
        "procedencia": "parcial - evento confirmado no PDF, resto NAO CONFIRMADO",
        "porQueLer": "Resumo apresentado no XXVIII Simposio de Ciencias Aplicadas / VII Simposio Internacional da FAEF.",
        "comoUsar": "Uso restrito: eventualmente como registro de divulgacao em portugues, nunca como evidencia.",
        "arquivo": "PDF/SINDROME DE PANDORA PREVENCAO.pdf",
        "referencia": "OLIVEIRA, V.; LEAL, R. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Sindrome de Pandora: prevencao",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "LITERATURA CINZENTA. Titulo, instituicao e ano NAO CONFIRMADOS.",
        "codigo": "S11",
        "grupo": "Contexto e revisao",
        "tipoEstudo": "TCC",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Material de apoio para contexto da area.",
        "comoUsar": "Apoio de leitura. Nao citar como fonte primaria.",
        "arquivo": "PDF_Para conhecimento/tcc_ Suzane Guimaraes.pdf",
        "referencia": "GUIMARAES, S. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo não localizado",
        "ano": "NAO CONFIRMADO",
        "titulo": "Trabalho de conclusao de curso (Suzane Guimaraes)",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "ARQUIVO INCOMPLETO: o PDF tem 1 pagina apenas (pagina 435, inicio do capitulo 47). Obter o capitulo completo antes de fichar. Marca de composicao no rodape indica 2005.",
        "codigo": "48",
        "grupo": "Fisiopatologia da FIC",
        "tipoEstudo": "Capitulo de livro",
        "procedencia": "parcial - autoria, capitulo e ano confirmados no PDF; obra e paginacao final NAO CONFIRMADAS",
        "porQueLer": "Capítulo clássico sobre a etiopatogênese da cistite idiopática felina, abordando os mecanismos envolvidos na condição.",
        "comoUsar": "Usar como base clínica para explicar a etiopatogênese da CIF e sua relação com a Síndrome de Pandora.",
        "arquivo": "PDF/ETIOPATHOGENESIS OF FELINE.pdf",
        "referencia": "WESTROPP, Jodi L.; BUFFINGTON, C. A. Tony. Etiopathogenesis of feline idiopathic cystitis. In: [OBRA NAO CONFIRMADA], cap. 47, p. 435-[final NAO CONFIRMADO], 2005.",
        "status": "arquivo obtido",
        "ano": "2005",
        "titulo": "Etiopathogenesis of Feline Idiopathic Cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado nesta pasta",
        "cautelas": "O fichamento desta fonte NAO esta nesta pasta, embora o acervo a registre como fichada.",
        "codigo": "S5",
        "grupo": "Fatores de risco comportamentais",
        "tipoEstudo": "Estudo retrospectivo",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Estudo retrospectivo de 336 gatos atendidos em clinica de comportamento em Barcelona.",
        "comoUsar": "Fornece fatores de risco comportamentais para cruzar com recorrencia da FIC.",
        "arquivo": "PDF/Primeiras Leituras/04_Potential risk factors associated with feline behaviour problems.pdf",
        "referencia": "AMAT, M. et al. Applied Animal Behaviour Science, v. 121, p. 134-139, 2009. DOI nao confirmado.",
        "status": "arquivo obtido",
        "ano": "2009",
        "titulo": "Potential risk factors associated with feline behaviour problems",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Essencial para Pandora, ambiente e comportamento. Não é artigo de IA.",
        "codigo": "53",
        "grupo": "Estresse, ambiente e comportamento",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Estudo observacional prospectivo que avaliou comportamentos de doença em resposta a eventos externos incomuns em gatos saudáveis e gatos com cistite intersticial felina.",
        "comoUsar": "Usar para justificar monitoramento ambiental, registro de eventos externos, rotina, comportamento do tutor e variáveis de estresse em ferramentas de IA.",
        "arquivo": "PDF/Sickness behaviors in response.pdf",
        "referencia": "NAO CONFIRMADO",
        "status": "fichamento concluido",
        "ano": "2011",
        "titulo": "Sickness behaviors in response to unusual external events in healthy cats and cats with feline interstitial cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "01_fichamento_stress_gatos_domesticos.pdf",
        "cautelas": "Ja fichada.",
        "codigo": "S4",
        "grupo": "Estresse e bem-estar em gatos domiciliados",
        "tipoEstudo": "Artigo de revisao",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Revisao sobre estressores do gato domiciliado e as mudancas comportamentais decorrentes.",
        "comoUsar": "Base do Nucleo 2 para definir estressores e sinais comportamentais mensuraveis.",
        "arquivo": "PDF/Primeiras Leituras/01_Stress in owned cats_behavioural.pdf",
        "referencia": "AMAT, M.; CAMPS, T.; MANTECA, X. Journal of Feline Medicine and Surgery, v. 18, n. 8, p. 577-586, 2016. DOI: 10.1177/1098612X15590867",
        "status": "fichamento concluido",
        "ano": "2016",
        "titulo": "Stress in owned cats: behavioural changes and welfare implications",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "Não priorizar.",
        "codigo": "46",
        "grupo": "Neoplasia do trato urinário inferior",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Não é FIC, mas é diagnóstico diferencial de sinais urinários.",
        "comoUsar": "Usar apenas em limites e diferenciais da ferramenta.",
        "arquivo": "",
        "referencia": "GRIFFIN, Maureen A.; CULP, William T. N.; REBHUN, Robert B. Lower urinary tract neoplasia. Veterinary Sciences, v. 5, n. 4, 2018. DOI: 10.3390/VETSCI5040096.",
        "status": "ainda nao obtido",
        "ano": "2018",
        "titulo": "Lower urinary tract neoplasia",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "03_fichamento_A systematic of social and environmental factors.pdf",
        "cautelas": "Ja fichada. Revisao sistematica: conferir criterios de inclusao antes de generalizar.",
        "codigo": "S1",
        "grupo": "Ambiente e bem-estar de gatos de interior",
        "tipoEstudo": "Revisao sistematica",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Revisao sistematica que reune os fatores sociais e ambientais que afetam o bem-estar do gato de interior.",
        "comoUsar": "Sustenta o Nucleo 2: ambiente como determinante, e base para escolher o que monitorar.",
        "arquivo": "PDF/A systematic review of social and environmental factors and their.pdf",
        "referencia": "FOREMAN-WORSLEY, R.; FARNWORTH, M. J. Applied Animal Behaviour Science, v. 220, art. 104841, 2019. DOI nao confirmado.",
        "status": "fichamento concluido",
        "ano": "2019",
        "titulo": "A systematic review of social and environmental factors and their implications for indoor cat welfare",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Muito útil para ferramenta de apoio.",
        "codigo": "31",
        "grupo": "Tutor, conhecimento e bem-estar felino",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Conecta atitudes do tutor, cuidado domiciliar, comportamento e bem-estar.",
        "comoUsar": "Usar para questionário de tutor e variáveis ambientais.",
        "arquivo": "",
        "referencia": "GRIGG, Emma K.; KOGAN, Lori R. Owners’ attitudes, knowledge, and care practices: Exploring the implications for domestic cat behavior and welfare in the home. Animals, v. 9, n. 11, 2019. DOI: 10.3390/ANI9110978.",
        "status": "ainda nao obtido",
        "ano": "2019",
        "titulo": "Owners’ attitudes, knowledge, and care practices: Exploring the implications for domestic cat behavior and welfare in the home",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Não é IA.",
        "codigo": "39",
        "grupo": "Dieta terapêutica e recorrência de FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Estudo sobre dieta urinária/stress diet e recorrência de FIC.",
        "comoUsar": "Usar em manejo e variáveis terapêuticas.",
        "arquivo": "",
        "referencia": "NAARDEN, Blanche; CORBEE, Ronald J. The effect of a therapeutic urinary stress diet on the short-term recurrence of feline idiopathic cystitis. Veterinary Medicine and Science, v. 6, n. 1, p. 32-38, 2020. DOI: 10.1002/vms3.197.",
        "status": "ainda nao obtido",
        "ano": "2020",
        "titulo": "The effect of a therapeutic urinary stress diet on the short-term recurrence of feline idiopathic cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Cautela: não é animais de companhia.",
        "codigo": "38",
        "grupo": "Sensores, big data e ML em animais",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Apoia sensores, big data e machine learning, embora foque produção animal.",
        "comoUsar": "Usar como analogia tecnológica para coleta contínua e modelos preditivos.",
        "arquivo": "",
        "referencia": "NEETHIRAJAN, Suresh. The role of sensors, big data and machine learning in modern animal farming. Sensing and Bio-Sensing Research, v. 29, 2020. DOI: 10.1016/j.sbsr.2020.100367.",
        "status": "ainda nao obtido",
        "ano": "2020",
        "titulo": "The role of sensors, big data and machine learning in modern animal farming",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Importante para conversar com o veterinário.",
        "codigo": "21",
        "grupo": "Patogênese e histopatologia da FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Base forte para fisiopatologia e comparação da FIC.",
        "comoUsar": "Usar para fundamentar o problema clínico e selecionar variáveis.",
        "arquivo": "",
        "referencia": "JONES, Emily et al. Feline Idiopathic Cystitis: Pathogenesis, Histopathology and Comparative Potential. Journal of Comparative Pathology, v. 185, p. 18-29, 2021. DOI: 10.1016/j.jcpa.2021.03.006.",
        "status": "ainda nao obtido",
        "ano": "2021",
        "titulo": "Feline Idiopathic Cystitis: Pathogenesis, Histopathology and Comparative Potential",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Título possui erro de grafia no Zotero; corrigir.",
        "codigo": "13",
        "grupo": "Lacunas da IA veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Mostra potencial não explorado da IA veterinária.",
        "comoUsar": "Usar para justificar lacunas, oportunidades e necessidade de novas ferramentas.",
        "arquivo": "",
        "referencia": "BASRAN, Parminder S.; APPLEBY, Ryan B. The unmet potential of artificial intelligencin veterinary medicine. American Journal of Veterinary Research, v. 83, n. 5, p. 385-392, 2022. DOI: 10.2460/AJVR.22.03.0038.",
        "status": "ainda nao obtido",
        "ano": "2022",
        "titulo": "The unmet potential of artificial intelligencin veterinary medicine",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Apoia monitoramento comportamental.",
        "codigo": "32",
        "grupo": "Bem-estar e brincadeira em gatos",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Ajuda a transformar bem-estar e comportamento em variáveis observáveis.",
        "comoUsar": "Usar para ambiente, enriquecimento, rotina e dados do tutor.",
        "arquivo": "",
        "referencia": "HENNING, Julia et al. Cats just want to have fun: Associations between play and welfare in domestic cats. Animal Welfare, v. 32, 2023. DOI: 10.1017/AWF.2023.2.",
        "status": "ainda nao obtido",
        "ano": "2023",
        "titulo": "Cats just want to have fun: Associations between play and welfare in domestic cats",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Não é veterinário clínico, mas é relevante.",
        "codigo": "33",
        "grupo": "Ética: dano a animais por IA",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Dá base ética ampla sobre riscos da IA para animais não humanos.",
        "comoUsar": "Usar para limites, vieses, monitoramento invasivo e proteção do bem-estar.",
        "arquivo": "",
        "referencia": "COGHLAN, Simon; PARKER, Christine. Harm to Nonhuman Animals from AI: a Systematic Account and Framework. Philosophy and Technology, v. 36, n. 2, 2023. DOI: 10.1007/S13347-023-00627-6.",
        "status": "ainda nao obtido",
        "ano": "2023",
        "titulo": "Harm to Nonhuman Animals from AI: a Systematic Account and Framework",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "Não é ferramenta de IA.",
        "codigo": "44",
        "grupo": "Cistite intersticial comparativa",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Pode ajudar na comparação entre fatores de risco/proteção, mas é fonte de dor/cistite intersticial mais ampla.",
        "comoUsar": "Usar apenas para discussão comparativa, não como base principal da FIC felina.",
        "arquivo": "",
        "referencia": "WESTROPP, Jodi L.; STELLA, Judith L.; BUFFINGTON, C. A. Tony. Interstitial cystitis—an imbalance of risk and protective factors?. Frontiers in Pain Research, v. 5, 2024. DOI: 10.3389/FPAIN.2024.1405488.",
        "status": "ainda nao obtido",
        "ano": "2024",
        "titulo": "Interstitial cystitis—an imbalance of risk and protective factors?",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para tese.",
        "codigo": "9",
        "grupo": "IA na prática clínica veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Discute aplicação potencial da IA na prática clínica e pesquisa biomédica veterinária.",
        "comoUsar": "Usar para conectar IA à rotina clínica e ao apoio ao veterinário.",
        "arquivo": "PDF/Relevantes/The potential application of.pdf",
        "referencia": "AKINSULIE, Olalekan Chris et al. The potential application of artificial intelligence in veterinary clinical practice and biomedical research. Frontiers in Veterinary Science, v. 11, 2024. DOI: 10.3389/FVETS.2024.1347550.",
        "status": "arquivo obtido",
        "ano": "2024",
        "titulo": "The potential application of artificial intelligence in veterinary clinical practice and biomedical research",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para governança de ferramentas.",
        "codigo": "12",
        "grupo": "Governança de IA em imagem veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Posicionamento de entidades de radiologia veterinária sobre IA.",
        "comoUsar": "Usar para validação, governança, segurança, responsabilidade e limites.",
        "arquivo": "",
        "referencia": "APPLEBY, Ryan B. et al. American College of Veterinary Radiology and European College of Veterinary Diagnostic Imaging position statement on artificial intelligence. Journal of the American Veterinary Medical Association, v. 263, n. 6, p. 773-776, 2025. DOI: 10.2460/javma.25.01.0027.",
        "status": "ainda nao obtido",
        "ano": "2025",
        "titulo": "American College of Veterinary Radiology and European College of Veterinary Diagnostic Imaging position statement on artificial intelligence",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Muito forte para metodologia/proposta.",
        "codigo": "4",
        "grupo": "Ferramenta com prontuário veterinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Exemplo concreto de plataforma open-source integrando classificadores de ML ao prontuário eletrônico veterinário.",
        "comoUsar": "Usar como modelo de arquitetura para ferramenta de apoio à decisão.",
        "arquivo": "PDF/Relevantes/Anna.pdf",
        "referencia": "KONG, Chun Yin et al. Anna: an open-source platform for real-time integration of machine learning classifiers with veterinary electronic health records. BMC Veterinary Research, v. 21, n. 1, 2025. DOI: 10.1186/S12917-025-05000-7.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Anna: an open-source platform for real-time integration of machine learning classifiers with veterinary electronic health records",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para IA.",
        "codigo": "8",
        "grupo": "Revisão narrativa IA veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão útil para aplicações e cuidados no uso de IA nas ciências veterinárias.",
        "comoUsar": "Usar como suporte teórico e tecnológico.",
        "arquivo": "",
        "referencia": "AKBAREIN, Hesameddin et al. Applications and Considerations of Artificial Intelligence in Veterinary Sciences: A Narrative Review. Veterinary Medicine and Science, v. 11, n. 3, 2025. DOI: 10.1002/vms3.70315.",
        "status": "ainda nao obtido",
        "ano": "2025",
        "titulo": "Applications and Considerations of Artificial Intelligence in Veterinary Sciences: A Narrative Review",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Não é específico de gatos/FIC.",
        "codigo": "35",
        "grupo": "IA em imagem diagnóstica",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Exemplo de IA aplicada à radiografia; não é urinário, mas é relevante como evidência de maturidade em imagem.",
        "comoUsar": "Usar como exemplo de ferramenta diagnóstica veterinária já mais madura.",
        "arquivo": "",
        "referencia": "RUBINI, Andrea et al. Artificial Intelligence in Chest Radiography—A Comparative Review of Human and Veterinary Medicine. Veterinary Sciences, v. 12, n. 5, 2025. DOI: 10.3390/VETSCI12050404.",
        "status": "ainda nao obtido",
        "ano": "2025",
        "titulo": "Artificial Intelligence in Chest Radiography—A Comparative Review of Human and Veterinary Medicine",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para eixo de ferramentas.",
        "codigo": "3",
        "grupo": "Saúde digital de animais de companhia",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Conecta IA, saúde digital, tutores e animais de companhia.",
        "comoUsar": "Usar para justificar dados domiciliares, tutores, acompanhamento e medicina digital.",
        "arquivo": "PDF/Relevantes/Artificial intelligence and companion animals.pdf",
        "referencia": "ARSHAD, Muhammad Furqan et al. Artificial intelligence and companion animals: Perspectives on digital healthcare for dogs, cats, and pet ownership. Research in Veterinary Science, v. 193, 2025. DOI: 10.1016/J. RVSC.2025.105776.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Artificial intelligence and companion animals: Perspectives on digital healthcare for dogs, cats, and pet ownership",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para tese.",
        "codigo": "7",
        "grupo": "IA veterinária: aplicações e desafios",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Panorama amplo e atual sobre aplicações, desafios e perspectivas da IA veterinária.",
        "comoUsar": "Usar na contextualização geral do campo e lacunas.",
        "arquivo": "PDF/Relevantes/Artificial intelligence in veterinary and animal science.pdf",
        "referencia": "HOSSEIN-ZADEH, Navid Ghavi. Artificial intelligence in veterinary and animal science: applications, challenges, and future prospects. Computers and Electronics in Agriculture, v. 235, 2025. DOI: 10.1016/J. COMPAG.2025.110395.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Artificial intelligence in veterinary and animal science: applications, challenges, and future prospects",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Muito importante para a tese.",
        "codigo": "2",
        "grupo": "Maturidade da IA em pequenos animais",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Explica que a IA já cria valor em algumas áreas e ainda é imatura em outras.",
        "comoUsar": "Usar para justificar ferramentas inexistentes ou em estágio experimental.",
        "arquivo": "PDF/Relevantes/Artificial intelligence is beginning to create value for selected.pdf",
        "referencia": "ALBERGANTE, Luca; O’FLYNN, Ciaran; DE MEYER, Geert. Artificial intelligence is beginning to create value for selected small animal veterinary applications while remaining immature for others. Journal of the American Veterinary Medical Association, v. 263, n. 3, p. 388-394, 2025. DOI: 10.2460/JAVMA.24.09.0617.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Artificial intelligence is beginning to create value for selected small animal veterinary applications while remaining immature for others",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Muito forte para a tese. Artigo clínico/comportamental, não de IA.",
        "codigo": "49",
        "grupo": "Estresse, comportamento e recorrência",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Investiga associação entre fatores comportamentais, medo, ansiedade e recorrência da CIF em gatos.",
        "comoUsar": "Usar para justificar questionários do tutor, monitoramento comportamental, previsão de recorrência e variáveis comportamentais em ferramentas de IA.",
        "arquivo": "PDF/Relevantes/Association between behavioral factors and recurrence rate in cats with.pdf",
        "referencia": "NAO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Association between behavioral factors and recurrence rate in cats with feline “idiopathic” cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Não é evidência clínica robusta.",
        "codigo": "23",
        "grupo": "Transformação da veterinária por IA",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Editorial/visão geral sobre transformação da medicina veterinária por IA.",
        "comoUsar": "Usar com moderação na introdução ou discussão de tendências.",
        "arquivo": "",
        "referencia": "NAO CONFIRMADO",
        "status": "ainda nao obtido",
        "ano": "2025",
        "titulo": "From bark to bytes: artificial intelligence transforming veterinary medicine",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Forte para ferramenta. Não é IA, mas fornece variável objetiva.",
        "codigo": "52",
        "grupo": "Biomarcadores e dados laboratoriais",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Avalia a relação neutrófilo-linfócito como biomarcador não invasivo para auxiliar no diagnóstico da CIF.",
        "comoUsar": "Usar como biomarcador simples para entrada de dados, triagem clínica, classificação de risco e apoio à decisão veterinária.",
        "arquivo": "",
        "referencia": "NAO CONFIRMADO",
        "status": "ainda nao obtido",
        "ano": "2025",
        "titulo": "Neutrophil-to-Lymphocyte Ratio as a Promising Non-Invasive Biomarker for Diagnosis of Feline Idiopathic Cystitis in Cats",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para ferramentas.",
        "codigo": "5",
        "grupo": "Sensores e sinais vitais remotos",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Base tecnológica para monitoramento remoto, sinais vitais e coleta de dados clínicos.",
        "comoUsar": "Usar para justificar sensores, telemetria e monitoramento domiciliar ou clínico.",
        "arquivo": "PDF/Relevantes/Remote Vital Sensing in Clinical Veterinary Medicine.pdf",
        "referencia": "ZHAO, Xinyue et al. Remote Vital Sensing in Clinical Veterinary Medicine: A Comprehensive Review of Recent Advances, Accomplishments, Challenges, and Future Perspectives. Animals, v. 15, n. 7, 2025. DOI: 10.3390/ANI15071033.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Remote Vital Sensing in Clinical Veterinary Medicine: A Comprehensive Review of Recent Advances, Accomplishments, Challenges, and Future Perspectives",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para IA.",
        "codigo": "6",
        "grupo": "Deep learning em diagnóstico veterinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão central sobre deep learning em diagnóstico veterinário e saúde animal.",
        "comoUsar": "Usar na base metodológica de IA, tipos de dados e modelos.",
        "arquivo": "PDF/Relevantes/Review of applications of deep.pdf",
        "referencia": "XIAO, Sam et al. Review of applications of deep learning in veterinary diagnostics and animal health. Frontiers in Veterinary Science, v. 12, 2025. DOI: 10.3389/FVETS.2025.1511522.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Review of applications of deep learning in veterinary diagnostics and animal health",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Clínico/epidemiológico.",
        "codigo": "36",
        "grupo": "Séries temporais e obstrução uretral",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Dados temporais sobre obstrução uretral em gatos machos, útil para risco e sazonalidade.",
        "comoUsar": "Usar para variáveis temporais, tendência, alerta e contexto brasileiro.",
        "arquivo": "",
        "referencia": "DE MORAES, Reiner Silveira et al. Characterization and comparative analysis of urinary bacterial microbiome profiling in healthy cats and cats with feline idiopathic cystitis. Scientific Reports, v. 15, n. 1, p. 28211-, 2025. DOI: 10.1038/s41598-025-12360-5.",
        "status": "ainda nao obtido",
        "ano": "2025",
        "titulo": "Time series analysis of urethral obstruction in male cats in a veterinary teaching hospital in São paulo, Brazil",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para base clínica.",
        "codigo": "16",
        "grupo": "Manejo baseado em evidências da FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão sistemática sobre estratégias de manejo de FIC recorrente.",
        "comoUsar": "Usar para separar recomendações fortes, fracas e lacunas que a ferramenta pode apoiar.",
        "arquivo": "PDF/Relevantes/Understanding_the_current_evidence_base_for_the_commonly_recommended_management_strategies_for_recurrent_feline_idiopath.pdf",
        "referencia": "MACLEOD, B. et al. Understanding the current evidence base for the commonly recommended management strategies for recurrent feline idiopathic cystitis: a systematic review. New Zealand Veterinary Journal, v. 73, n. 4, p. 233-245, 2025. DOI: 10.1080/00480169.2025.2477542.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Understanding the current evidence base for the commonly recommended management strategies for recurrent feline idiopathic cystitis: a systematic review",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Mais amplo que gatos/FIC.",
        "codigo": "25",
        "grupo": "Tecnologias inteligentes e monitoramento",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Apoia a discussão sobre dispositivos inteligentes, monitoramento e tecnologias veterinárias de precisão.",
        "comoUsar": "Usar como base tecnológica complementar para sensores e coleta contínua.",
        "arquivo": "",
        "referencia": "JHILTA, Agrim et al. Advanced precision veterinary technologies and smart boluses: Innovations in drug delivery, health monitoring, and future perspectives. Journal of Drug Delivery Science and Technology, v. 115, 2026. DOI: 10.1016/j.jddst.2025.107563.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Advanced precision veterinary technologies and smart boluses: Innovations in drug delivery, health monitoring, and future perspectives",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Apoio educacional veterinário, não ferramenta clínica direta.",
        "codigo": "22",
        "grupo": "Letramento e adoção de IA veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Ajuda a explicar por que veterinários precisam compreender IA para usar ferramentas de apoio com segurança.",
        "comoUsar": "Usar na seção de capacitação, limites de decisão e responsabilidade profissional.",
        "arquivo": "",
        "referencia": "HUANG, Yi-Ting; CHU, Candice P. Curriculum framework for artificial intelligence literacy in veterinary education. Frontiers in Veterinary Science, v. 13, 2026. DOI: 10.3389/fvets.2026.1801756.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Curriculum framework for artificial intelligence literacy in veterinary education",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "Cautela: preprint/relato de caso; não usar como base central.",
        "codigo": "47",
        "grupo": "Diagnóstico diferencial urinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Relato/revisão sobre cistite pseudomembranosa; útil para diferencial, mas não representa FIC/Pandora.",
        "comoUsar": "Usar para mostrar que a ferramenta deve evitar classificar toda cistite como FIC.",
        "arquivo": "PDF/Diagnosis and Management of.pdf",
        "referencia": "SHI, Qian et al. Diagnosis and Management of Pseudomembranous Cystitis in Cat: A Case Report and Review of Literature. [periodico NAO CONFIRMADO], 2026. DOI: 10.20944/preprints202605.0381.v1.",
        "status": "arquivo obtido",
        "ano": "2026",
        "titulo": "Diagnosis and Management of Pseudomembranous Cystitis in Cat: A Case Report and Review of Literature",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Conferir qualidade da fonte antes de usar como referência central.",
        "codigo": "30",
        "grupo": "Estresse, ambiente e comportamento felino",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Relaciona ambiente urbano, estresse crônico e saúde física/comportamental dos gatos.",
        "comoUsar": "Usar para justificar dados ambientais, rotina, enriquecimento, sinais de estresse e questionário do tutor.",
        "arquivo": "PDF/Estresse+em+gatos+domesticos_+impacto+do+ambiente+urbano.EDITADO+..pdf",
        "referencia": "QUEIROZ, Beatriz Lopes; QUEIROZ, Hélio Lemes. Estresse em gatos domésticos: impacto do ambiente urbano na saúde física e comportamental. Revista ft, v. 30, n. 158, p. 01-23, 2026. DOI: 10.69849/y3zpv398.",
        "status": "arquivo obtido",
        "ano": "2026",
        "titulo": "Estresse em gatos domésticos: impacto do ambiente urbano na saúde física e comportamental",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para ferramentas de IA.",
        "codigo": "10",
        "grupo": "Ética em IA para pequenos animais",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Essencial para discutir responsabilidade, limites da IA e segurança em pequenos animais.",
        "comoUsar": "Usar na seção de ética, governança, decisão assistida e proteção do animal.",
        "arquivo": "",
        "referencia": "COGHLAN, Simon; QUINN, Thomas. Ethical Considerations for Artificial Intelligence Tools in Small Animal Veterinary Medicine. Veterinary Clinics of North America: Small Animal Practice, 2026. DOI: 10.1016/J. CVSM.2026.03.001.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Ethical Considerations for Artificial Intelligence Tools in Small Animal Veterinary Medicine",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para segurança e responsabilidade.",
        "codigo": "11",
        "grupo": "Ética e tomada de decisão veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Diretamente ligado à tomada de decisão veterinária com IA.",
        "comoUsar": "Usar para delimitar que a ferramenta auxilia, mas não substitui o veterinário.",
        "arquivo": "",
        "referencia": "HEINLEIN, Matt. Ethical considerations of artificial intelligence in veterinary medicine decision-making. Frontiers in Veterinary Science, v. 13, 2026. DOI: 10.3389/FVETS.2026.1780868.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Ethical considerations of artificial intelligence in veterinary medicine decision-making",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Cautela: arXiv/preprint e validação clínica ainda limitada.",
        "codigo": "14",
        "grupo": "IA multimodal e etologia felina",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "É o artigo mais próximo de uma ferramenta de IA voltada especificamente à interpretação multimodal do comportamento felino.",
        "comoUsar": "Usar como tendência/protótipo de IA multimodal para comportamento, sinais fisiológicos e apoio ao raciocínio veterinário.",
        "arquivo": "PDF/Relevantes/Meow-Omni 1.pdf",
        "referencia": "HU, Jucheng et al. Meow-Omni 1: A Multimodal Large Language Model for Feline Ethology. [periodico NAO CONFIRMADO], 2026. Disponivel em: https://arxiv.org/pdf/2605.09152.",
        "status": "arquivo obtido",
        "ano": "2026",
        "titulo": "Meow-Omni 1: A Multimodal Large Language Model for Feline Ethology",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Muito útil para conversar com o veterinário.",
        "codigo": "28",
        "grupo": "Diagnóstico diferencial e análise multimodal",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Importante para evitar confusão entre bacteriúria/piúria subclínica e doença urinária ativa.",
        "comoUsar": "Usar para regras de exclusão, segurança clínica e lógica multimodal da ferramenta.",
        "arquivo": "",
        "referencia": "TALLAKSEN, Jessica M et al. Subclinical bacteriuria and pyuria in companion animals without signs of lower urinary tract disease: prevalence and associations in a prospective cross-sectional study using multimodal analytics. Journal of Veterinary Internal Medicine, n. 1, p. 92, 2026. DOI: 10.1093/jvimsj/aalaf092.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Subclinical bacteriuria and pyuria in companion animals without signs of lower urinary tract disease: prevalence and associations in a prospective cross-sectional study using multimodal analytics",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Base de revisão sistemática; priorizar na conversa com o veterinário.",
        "codigo": "1",
        "grupo": "IA em animais de companhia",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão sistemática diretamente alinhada ao eixo da tese: IA em animais de companhia, comportamento, bem-estar e diagnóstico.",
        "comoUsar": "Usar para abrir o referencial de IA aplicada a cães/gatos e para justificar a lacuna em comportamento felino e monitoramento contínuo.",
        "arquivo": "PDF/Relevantes/The Expanding Role of Artificial Intelligence in Companion.pdf",
        "referencia": "SABOLEK, Ivana; JOVIĆ, Alan. The Expanding Role of Artificial Intelligence in Companion Animal Care: A Systematic Review. Animals, v. 16, n. 7, p. 1035, 2026. DOI: 10.3390/ANI16071035/S1.",
        "status": "arquivo obtido",
        "ano": "2026",
        "titulo": "The Expanding Role of Artificial Intelligence in Companion Animal Care: A Systematic Review",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Contexto geográfico específico: China.",
        "codigo": "20",
        "grupo": "Adoção de IA por veterinários",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Mostra adoção elevada com baixa familiaridade, importante para discutir barreiras reais de implementação.",
        "comoUsar": "Usar na discussão sobre confiança, treinamento e interface das ferramentas de IA.",
        "arquivo": "",
        "referencia": "LI, Shumin; LAI, Xiaoyun. The adoption paradox for veterinary professionals in China: high use of artificial intelligence despite low familiarity. Frontiers in Veterinary Science, v. 13, 2026. DOI: 10.3389/fvets.2026.1727001.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "The adoption paradox for veterinary professionals in China: high use of artificial intelligence despite low familiarity",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Ênfase em imagem diagnóstica.",
        "codigo": "18",
        "grupo": "Adoção de IA e diagnóstico por imagem",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Mostra percepção de trabalhadores veterinários sobre IA, conhecimento baixo e atitude positiva.",
        "comoUsar": "Usar para justificar educação, validação e aceitação profissional.",
        "arquivo": "",
        "referencia": "OFER, Oren et al. Veterinary workers report low knowledge of artificial intelligence but positive attitudes toward its adoption in diagnostic imaging and the workplace as a whole. Journal of the American Veterinary Medical Association, p. 1-7, 2026. DOI: 10.2460/JAVMA.25.08.0545.",
        "status": "ainda nao obtido",
        "ano": "2026",
        "titulo": "Veterinary workers report low knowledge of artificial intelligence but positive attitudes toward its adoption in diagnostic imaging and the workplace as a whole",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Ano 2006 aparece no nome do arquivo, nao foi confirmado no documento.",
        "codigo": "S2",
        "grupo": "Manejo ambiental multimodal (MEMO)",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Estudo classico que testa a modificacao ambiental multimodal como manejo da cistite idiopatica.",
        "comoUsar": "E a intervencao que fecha o argumento: se o ambiente causa, o ambiente tratado reduz o problema.",
        "arquivo": "PDF/buffington-et-al-2006-clinical-evaluation-of-multimodal-environmental-modification-(memo)-in-the-management-of-cats.pdf",
        "referencia": "BUFFINGTON, C. A. T. et al. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Clinical evaluation of multimodal environmental modification (MEMO) in the management of cats with idiopathic cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Ano, volume e paginacao NAO CONFIRMADOS (Scientific Reports).",
        "codigo": "S6",
        "grupo": "Avaliacao de dor por expressao facial",
        "tipoEstudo": "Estudo prospectivo caso-controle",
        "procedencia": "parcial - autoria confirmada no PDF, resto NAO CONFIRMADO",
        "porQueLer": "Desenvolve e valida a Feline Grimace Scale para detectar dor aguda por unidades de acao facial.",
        "comoUsar": "Unico instrumento validado de leitura de sinal clinico por imagem no acervo: ponte entre o Nucleo 1 e a captura por sensor/visao computacional.",
        "arquivo": "PDF/Facial expressions of pain in cats.pdf",
        "referencia": "EVANGELISTA, M. C. et al. Scientific Reports. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Facial expressions of pain in cats: the development and validation of a Feline Grimace Scale",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    }
];
