window.DADOS_INVENTARIO = [
    {
        "fase": "Ler primeiro",
        "fichamento": "50 — Fichamento — Small adrenal glands in cats with FIC.md",
        "cautelas": "Essencial para a visão sistêmica da Pandora. Artigo antigo, mas muito importante.",
        "codigo": "50",
        "grupo": "Síndrome de Pandora e eixo neuroendócrino",
        "tipoEstudo": "Estudo experimental comparativo, com teste de estimulação por ACTH, dosagem de cortisol, análise morfométrica e avaliação histológica das glândulas adrenais de gatos saudáveis e gatos com cistite intersticial felina.",
        "procedencia": "preenchida por voce na triagem",
        "porQueLer": "Estudo clássico que relaciona alterações adrenais, eixo hipotálamo hipófise adrenal e cistite intersticial felina.",
        "comoUsar": "Usar como base neuroendócrina para discutir estresse, eixo HHA, adrenal e resposta fisiológica na Síndrome de Pandora.",
        "arquivo": "PDF/Primeiras Leituras/02_SMALL ADRENAL GLANDS IN CATS WITH FELINE INTERSTITIAL.pdf",
        "referencia": "WESTROPP, Jodi L.; WELK, Kristin A.; BUFFINGTON, C. A. Tony. Small adrenal glands in cats with feline interstitial cystitis. The Journal of Urology, v. 170, n. 6 Pt 1, p. 2494–2497, 2003. DOI: 10.1097/01.ju.0000095566.63870.66.",
        "status": "fichamento concluido",
        "ano": "2003",
        "titulo": "Small adrenal glands in cats with feline interstitial cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "43 — Fichamento — Changing Paradigms of Feline Idiopathic Cystitis.md",
        "cautelas": "Artigo antigo; usar com revisões recentes.",
        "codigo": "43",
        "grupo": "Mudança de paradigma em FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Base conceitual para evolução histórica da compreensão da FIC.",
        "comoUsar": "Usar na introdução clínica/histórica.",
        "arquivo": "PDF/Síndrome CIF/Changing Paradigms.pdf",
        "referencia": "KRUGER, John M.; OSBORNE, Carl A.; LULICH, Jody P. Changing Paradigms of Feline Idiopathic Cystitis. Veterinary Clinics of North America - Small Animal Practice, v. 39, n. 1, p. 15-40, 2009. DOI: 10.1016/j.cvsm.2008.09.008.",
        "status": "fichamento concluido",
        "ano": "2009",
        "titulo": "Changing Paradigms of Feline Idiopathic Cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "19 — Fichamento — Idiopathic Cystitis Beyond LUT.md",
        "cautelas": "Muito importante.",
        "codigo": "19",
        "grupo": "Síndrome de Pandora / além do trato urinário",
        "tipoEstudo": "revisao narrativa",
        "procedencia": "confirmada no PDF (26/09/2026)",
        "porQueLer": "Essencial para sustentar que o problema ultrapassa a bexiga e envolve estresse/sistema.",
        "comoUsar": "Usar para a transição FIC → Síndrome de Pandora e ferramenta sistêmica.",
        "arquivo": "PDF/Síndrome CIF/j.1939-1676.2011.0732.x.pdf",
        "referencia": "BUFFINGTON, C. A. Tony. Idiopathic cystitis in domestic cats-beyond the lower urinary tract. Journal of Veterinary Internal Medicine, v. 25, n. 4, p. 784-796, 2011. DOI: 10.1111/j.1939-1676.2011.0732.x.",
        "status": "fichamento concluido",
        "ano": "2011",
        "titulo": "Idiopathic cystitis in domestic cats-beyond the lower urinary tract",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "51 — Fichamento — From FUS to Pandora syndrome.md",
        "cautelas": "Leitura obrigatória. Usar na introdução e justificativa.",
        "codigo": "51",
        "grupo": "Síndrome de Pandora e mudança conceitual",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Artigo central sobre a evolução conceitual de FUS e CIF para Síndrome de Pandora.",
        "comoUsar": "Usar como base conceitual principal para justificar que o foco da pesquisa deve ser Síndrome de Pandora, e não apenas cistite.",
        "arquivo": "PDF/Primordiais/tony-buffington-et-al-2014-from-fus-to-pandora-syndrome.pdf",
        "referencia": "NAO CONFIRMADO",
        "status": "fichamento concluido",
        "ano": "2014",
        "titulo": "From FUS to Pandora syndrome: Where are we, how did we get here, and where to now?",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "40 — Fichamento — Feline Idiopathic Cystitis (VCNA 2015).md",
        "cautelas": "Artigo mais antigo, não substituir revisões recentes.",
        "codigo": "40",
        "grupo": "Revisão clínica FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão clínica útil para alinhamento com o veterinário.",
        "comoUsar": "Usar como apoio clínico, especialmente para linguagem veterinária.",
        "arquivo": "PDF/Síndrome CIF/Feline_idiopathic_cystitis_VCNA_2015.pdf",
        "referencia": "FORRESTER, S. Dru; TOWELL, Todd L. Feline Idiopathic Cystitis. Veterinary Clinics of North America - Small Animal Practice, v. 45, n. 4, p. 783-806, 2015. DOI: 10.1016/j.cvsm.2015.02.007.",
        "status": "fichamento concluido",
        "ano": "2015",
        "titulo": "Feline Idiopathic Cystitis",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "17 — Fichamento — FIC update review.md",
        "cautelas": "Essencial.",
        "codigo": "17",
        "grupo": "Revisão FIC: risco, biomarcadores e manejo",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Artigo guarda-chuva para FIC: prevalência, fatores de risco, biomarcadores e manejo.",
        "comoUsar": "Usar como base clínica principal para o problema-alvo.",
        "arquivo": "PDF/Síndrome CIF/Prevalence, Risk Factors,.pdf",
        "referencia": "HE, Chengxi et al. Prevalence, Risk Factors, Pathophysiology, Potential Biomarkers and Management of Feline Idiopathic Cystitis: An Update Review. Frontiers in Veterinary Science, v. 9, 2022. DOI: 10.3389/fvets.2022.900847.",
        "status": "fichamento concluido",
        "ano": "2022",
        "titulo": "Prevalence, Risk Factors, Pathophysiology, Potential Biomarkers and Management of Feline Idiopathic Cystitis: An Update Review",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado",
        "cautelas": "Contexto dos EUA. Ano vem do nome do arquivo, NAO CONFIRMADO no documento.",
        "codigo": "S9",
        "grupo": "Pratica clinica e conduta terapeutica",
        "tipoEstudo": "Survey",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Levantamento sobre como veterinarios nos EUA tratam FLUTD nao obstrutiva.",
        "comoUsar": "Mostra a distancia entre evidencia e pratica: util na justificativa de uma ferramenta de apoio.",
        "arquivo": "PDF/Síndrome CIF/krause-et-al-2024-survey-of-veterinarians-in-the-usa-to-evaluate-trends-in-the-treatment-approach-for-non-obstructive.pdf",
        "referencia": "KRAUSE et al. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "2024",
        "titulo": "Survey of veterinarians in the USA to evaluate trends in the treatment approach for non-obstructive FLUTD",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Verificar metadados, pois o título está traduzido.",
        "codigo": "26",
        "grupo": "Microbioma urinário e FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Conecta microbioma urinário, gatos saudáveis e FIC, útil para variáveis clínicas e discussão diagnóstica.",
        "comoUsar": "Usar em microbioma, exames complementares e limites da interpretação clínica.",
        "arquivo": "PDF/Síndrome CIF/Characterization and comparative.pdf",
        "referencia": "THASSAKORN, P et al. Characterization and comparative analysis of urinary bacterial microbiome profiling in healthy cats and cats with feline idiopathic cystitis. Scientific Reports, 2026. DOI: 10.1038/s41598-025-34196-9.",
        "status": "arquivo obtido",
        "ano": "2026",
        "titulo": "Caracterização e análise comparativa do perfil do microbioma bacteriano urinário em gatos saudáveis e gatos com cistite idiopática felina.",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S3 — Fichamento — External and internal influences on disease risk.md",
        "cautelas": "Secao \"Reference Point\" (JAVMA). Ano, volume e paginacao NAO CONFIRMADOS.",
        "codigo": "S3",
        "grupo": "Risco de doenca, ambiente e fisiologia",
        "tipoEstudo": "Artigo de revisao/posicionamento",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Texto de Buffington que articula influencias externas e internas sobre o risco de adoecer.",
        "comoUsar": "Ponte conceitual entre ambiente e fisiologia, anterior a formulacao da Sindrome de Pandora.",
        "arquivo": "PDF/Primordiais/External and internal influences.pdf",
        "referencia": "BUFFINGTON, C. A. T. Referencia completa NAO CONFIRMADA.",
        "status": "fichamento concluido",
        "ano": "NAO CONFIRMADO",
        "titulo": "External and internal influences on disease risk in cats",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "LITERATURA CINZENTA. Resumo de evento, sem revisao por pares. Ano NAO CONFIRMADO.",
        "codigo": "S8",
        "grupo": "Prevencao da Sindrome de Pandora",
        "tipoEstudo": "Resumo de evento",
        "procedencia": "parcial - evento confirmado no PDF, resto NAO CONFIRMADO",
        "porQueLer": "Resumo apresentado no XXVIII Simposio de Ciencias Aplicadas / VII Simposio Internacional da FAEF.",
        "comoUsar": "Uso restrito: eventualmente como registro de divulgacao em portugues, nunca como evidencia.",
        "arquivo": "PDF/Síndrome CIF/SÍNDROME DE PANDORA PREVENÇÃO.pdf",
        "referencia": "OLIVEIRA, V.; LEAL, R. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Sindrome de Pandora: prevencao",
        "nucleo": "Nucleo 1 - base historica, clinica e fisiologica"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "48 — Fichamento — Etiopathogenesis of Feline Idiopathic Cystitis.md",
        "cautelas": "ARQUIVO INCOMPLETO: o PDF tem 1 pagina apenas (pagina 435, inicio do capitulo 47). Obter o capitulo completo antes de fichar. Marca de composicao no rodape indica 2005.",
        "codigo": "48",
        "grupo": "Fisiopatologia da FIC",
        "tipoEstudo": "Capitulo de livro",
        "procedencia": "parcial - autoria, capitulo e ano confirmados no PDF; obra e paginacao final NAO CONFIRMADAS",
        "porQueLer": "Capítulo clássico sobre a etiopatogênese da cistite idiopática felina, abordando os mecanismos envolvidos na condição.",
        "comoUsar": "Usar como base clínica para explicar a etiopatogênese da CIF e sua relação com a Síndrome de Pandora.",
        "arquivo": "PDF/Síndrome CIF/ETIOPATHOGENESIS OF FELINE.pdf",
        "referencia": "WESTROPP, Jodi L.; BUFFINGTON, C. A. Tony. Etiopathogenesis of feline idiopathic cystitis. In: [OBRA NAO CONFIRMADA], cap. 47, p. 435-[final NAO CONFIRMADO], 2005.",
        "status": "fichamento concluido",
        "ano": "2005",
        "titulo": "Etiopathogenesis of Feline Idiopathic Cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "nao iniciado nesta pasta",
        "cautelas": "O fichamento desta fonte NAO esta nesta pasta, embora o acervo a registre como fichada.",
        "codigo": "S5",
        "grupo": "Fatores de risco comportamentais",
        "tipoEstudo": "Estudo retrospectivo",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Estudo retrospectivo de 336 gatos atendidos em clinica de comportamento em Barcelona.",
        "comoUsar": "Fornece fatores de risco comportamentais para cruzar com recorrencia da FIC.",
        "arquivo": "PDF/Primeiras Leituras/04_Potential risk factors associated with feline behaviour problems.pdf",
        "referencia": "AMAT, M. et al. Applied Animal Behaviour Science, v. 121, p. 134-139, 2009. DOI nao confirmado.",
        "status": "arquivo obtido",
        "ano": "2009",
        "titulo": "Potential risk factors associated with feline behaviour problems",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "53 — Fichamento — Sickness behaviors in response to unusual external events.md",
        "cautelas": "Essencial para Pandora, ambiente e comportamento. Não é artigo de IA.",
        "codigo": "53",
        "grupo": "Estresse, ambiente e comportamento",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Estudo observacional prospectivo que avaliou comportamentos de doença em resposta a eventos externos incomuns em gatos saudáveis e gatos com cistite intersticial felina.",
        "comoUsar": "Usar para justificar monitoramento ambiental, registro de eventos externos, rotina, comportamento do tutor e variáveis de estresse em ferramentas de IA.",
        "arquivo": "PDF/Síndrome CIF/Sickness behaviors in response.pdf",
        "referencia": "NAO CONFIRMADO",
        "status": "fichamento concluido",
        "ano": "2011",
        "titulo": "Sickness behaviors in response to unusual external events in healthy cats and cats with feline interstitial cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S4 — Fichamento — Stress in owned cats.md",
        "cautelas": "Ja fichada.",
        "codigo": "S4",
        "grupo": "Estresse e bem-estar em gatos domiciliados",
        "tipoEstudo": "Artigo de revisao",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Revisao sobre estressores do gato domiciliado e as mudancas comportamentais decorrentes.",
        "comoUsar": "Base do Nucleo 2 para definir estressores e sinais comportamentais mensuraveis.",
        "arquivo": "PDF/Primeiras Leituras/01_Stress in owned cats_behavioural.pdf",
        "referencia": "AMAT, M.; CAMPS, T.; MANTECA, X. Journal of Feline Medicine and Surgery, v. 18, n. 8, p. 577-586, 2016. DOI: 10.1177/1098612X15590867",
        "status": "fichamento concluido",
        "ano": "2016",
        "titulo": "Stress in owned cats: behavioural changes and welfare implications",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S1 — Fichamento — Social and environmental factors indoor cats.md",
        "cautelas": "Ja fichada. Revisao sistematica: conferir criterios de inclusao antes de generalizar.",
        "codigo": "S1",
        "grupo": "Ambiente e bem-estar de gatos de interior",
        "tipoEstudo": "Revisao sistematica",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Revisao sistematica que reune os fatores sociais e ambientais que afetam o bem-estar do gato de interior.",
        "comoUsar": "Sustenta o Nucleo 2: ambiente como determinante, e base para escolher o que monitorar.",
        "arquivo": "PDF/Primeiras Leituras/03_A systematic review of social and environmental factors.pdf",
        "referencia": "FOREMAN-WORSLEY, R.; FARNWORTH, M. J. Applied Animal Behaviour Science, v. 220, art. 104841, 2019. DOI nao confirmado.",
        "status": "fichamento concluido",
        "ano": "2019",
        "titulo": "A systematic review of social and environmental factors and their implications for indoor cat welfare",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para tese.",
        "codigo": "9",
        "grupo": "IA na prática clínica veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Discute aplicação potencial da IA na prática clínica e pesquisa biomédica veterinária.",
        "comoUsar": "Usar para conectar IA à rotina clínica e ao apoio ao veterinário.",
        "arquivo": "PDF/Síndrome CIF/The potential application of.pdf",
        "referencia": "AKINSULIE, Olalekan Chris et al. The potential application of artificial intelligence in veterinary clinical practice and biomedical research. Frontiers in Veterinary Science, v. 11, 2024. DOI: 10.3389/FVETS.2024.1347550.",
        "status": "arquivo obtido",
        "ano": "2024",
        "titulo": "The potential application of artificial intelligence in veterinary clinical practice and biomedical research",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "4 — Fichamento — Anna open-source platform ML classifiers EHR.md",
        "cautelas": "Muito forte para metodologia/proposta.",
        "codigo": "4",
        "grupo": "Ferramenta com prontuário veterinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Exemplo concreto de plataforma open-source integrando classificadores de ML ao prontuário eletrônico veterinário.",
        "comoUsar": "Usar como modelo de arquitetura para ferramenta de apoio à decisão.",
        "arquivo": "PDF/Síndrome CIF/Anna.pdf",
        "referencia": "KONG, Chun Yin et al. Anna: an open-source platform for real-time integration of machine learning classifiers with veterinary electronic health records. BMC Veterinary Research, v. 21, n. 1, 2025. DOI: 10.1186/S12917-025-05000-7.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Anna: an open-source platform for real-time integration of machine learning classifiers with veterinary electronic health records",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para eixo de ferramentas.",
        "codigo": "3",
        "grupo": "Saúde digital de animais de companhia",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Conecta IA, saúde digital, tutores e animais de companhia.",
        "comoUsar": "Usar para justificar dados domiciliares, tutores, acompanhamento e medicina digital.",
        "arquivo": "PDF/Síndrome CIF/Artificial intelligence and companion animals.pdf",
        "referencia": "ARSHAD, Muhammad Furqan et al. Artificial intelligence and companion animals: Perspectives on digital healthcare for dogs, cats, and pet ownership. Research in Veterinary Science, v. 193, 2025. DOI: 10.1016/J. RVSC.2025.105776.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Artificial intelligence and companion animals: Perspectives on digital healthcare for dogs, cats, and pet ownership",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para tese.",
        "codigo": "7",
        "grupo": "IA veterinária: aplicações e desafios",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Panorama amplo e atual sobre aplicações, desafios e perspectivas da IA veterinária.",
        "comoUsar": "Usar na contextualização geral do campo e lacunas.",
        "arquivo": "PDF/Síndrome CIF/Artificial intelligence in veterinary and animal science.pdf",
        "referencia": "HOSSEIN-ZADEH, Navid Ghavi. Artificial intelligence in veterinary and animal science: applications, challenges, and future prospects. Computers and Electronics in Agriculture, v. 235, 2025. DOI: 10.1016/J. COMPAG.2025.110395.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Artificial intelligence in veterinary and animal science: applications, challenges, and future prospects",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Muito importante para a tese.",
        "codigo": "2",
        "grupo": "Maturidade da IA em pequenos animais",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Explica que a IA já cria valor em algumas áreas e ainda é imatura em outras.",
        "comoUsar": "Usar para justificar ferramentas inexistentes ou em estágio experimental.",
        "arquivo": "PDF/Síndrome CIF/Artificial intelligence is beginning to create value for selected.pdf",
        "referencia": "ALBERGANTE, Luca; O'FLYNN, Ciaran; DE MEYER, Geert. Artificial intelligence is beginning to create value for selected small animal veterinary applications while remaining immature for others. Journal of the American Veterinary Medical Association, v. 263, n. 3, p. 388-394, 2025. DOI: 10.2460/JAVMA.24.09.0617.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Artificial intelligence is beginning to create value for selected small animal veterinary applications while remaining immature for others",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "49 — Fichamento — Behavioral factors and recurrence in FIC.md",
        "cautelas": "Muito forte para a tese. Artigo clínico/comportamental, não de IA.",
        "codigo": "49",
        "grupo": "Estresse, comportamento e recorrência",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Investiga associação entre fatores comportamentais, medo, ansiedade e recorrência da CIF em gatos.",
        "comoUsar": "Usar para justificar questionários do tutor, monitoramento comportamental, previsão de recorrência e variáveis comportamentais em ferramentas de IA.",
        "arquivo": "PDF/Síndrome CIF/Association between behavioral factors and recurrence rate in cats with.pdf",
        "referencia": "NAO CONFIRMADO",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Association between behavioral factors and recurrence rate in cats with feline \"idiopathic\" cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "nao iniciado",
        "cautelas": "Central para ferramentas.",
        "codigo": "5",
        "grupo": "Sensores e sinais vitais remotos",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Base tecnológica para monitoramento remoto, sinais vitais e coleta de dados clínicos.",
        "comoUsar": "Usar para justificar sensores, telemetria e monitoramento domiciliar ou clínico.",
        "arquivo": "PDF/Síndrome CIF/Remote Vital Sensing in Clinical Veterinary Medicine.pdf",
        "referencia": "ZHAO, Xinyue et al. Remote Vital Sensing in Clinical Veterinary Medicine: A Comprehensive Review of Recent Advances, Accomplishments, Challenges, and Future Perspectives. Animals, v. 15, n. 7, 2025. DOI: 10.3390/ANI15071033.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Remote Vital Sensing in Clinical Veterinary Medicine: A Comprehensive Review of Recent Advances, Accomplishments, Challenges, and Future Perspectives",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "6 — Fichamento — Deep learning in veterinary diagnostics.md",
        "cautelas": "Central para IA.",
        "codigo": "6",
        "grupo": "Deep learning em diagnóstico veterinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão central sobre deep learning em diagnóstico veterinário e saúde animal.",
        "comoUsar": "Usar na base metodológica de IA, tipos de dados e modelos.",
        "arquivo": "PDF/Síndrome CIF/Review of applications of deep.pdf",
        "referencia": "XIAO, Sam et al. Review of applications of deep learning in veterinary diagnostics and animal health. Frontiers in Veterinary Science, v. 12, 2025. DOI: 10.3389/FVETS.2025.1511522.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Review of applications of deep learning in veterinary diagnostics and animal health",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "16 — Fichamento — Evidence base management of recurrent FIC.md",
        "cautelas": "Central para base clínica.",
        "codigo": "16",
        "grupo": "Manejo baseado em evidências da FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão sistemática sobre estratégias de manejo de FIC recorrente.",
        "comoUsar": "Usar para separar recomendações fortes, fracas e lacunas que a ferramenta pode apoiar.",
        "arquivo": "PDF/Síndrome CIF/Understanding_the_current_evidence_base_for_the_commonly_recommended_management_strategies_for_recurrent_feline_idiopath.pdf",
        "referencia": "MACLEOD, B. et al. Understanding the current evidence base for the commonly recommended management strategies for recurrent feline idiopathic cystitis: a systematic review. New Zealand Veterinary Journal, v. 73, n. 4, p. 233-245, 2025. DOI: 10.1080/00480169.2025.2477542.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Understanding the current evidence base for the commonly recommended management strategies for recurrent feline idiopathic cystitis: a systematic review",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "25 — Fichamento — Advanced precision veterinary technologies smart boluses.md",
        "cautelas": "Mais amplo que gatos/FIC. ATENÇÃO: foco exclusivo em pecuária, gatos não são mencionados.",
        "codigo": "25",
        "grupo": "Tecnologias inteligentes e monitoramento",
        "tipoEstudo": "revisao narrativa",
        "procedencia": "confirmada no PDF (26/09/2026)",
        "porQueLer": "Apoia a discussão sobre dispositivos inteligentes, monitoramento e tecnologias veterinárias de precisão.",
        "comoUsar": "Usar como base tecnológica complementar para sensores e coleta contínua.",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S1773224725009669-main.pdf",
        "referencia": "JHILTA, Agrim et al. Advanced precision veterinary technologies and smart boluses: Innovations in drug delivery, health monitoring, and future perspectives. Journal of Drug Delivery Science and Technology, v. 115, artigo 107563, 2026. DOI: 10.1016/j.jddst.2025.107563.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Advanced precision veterinary technologies and smart boluses: Innovations in drug delivery, health monitoring, and future perspectives",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "nao iniciado",
        "cautelas": "Cautela: preprint/relato de caso; não usar como base central.",
        "codigo": "47",
        "grupo": "Diagnóstico diferencial urinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Relato/revisão sobre cistite pseudomembranosa; útil para diferencial, mas não representa FIC/Pandora.",
        "comoUsar": "Usar para mostrar que a ferramenta deve evitar classificar toda cistite como FIC.",
        "arquivo": "PDF/Síndrome CIF/Diagnosis_and_Management_of.pdf",
        "referencia": "SHI, Qian et al. Diagnosis and Management of Pseudomembranous Cystitis in Cat: A Case Report and Review of Literature. [periodico NAO CONFIRMADO], 2026. DOI: 10.20944/preprints202605.0381.v1.",
        "status": "arquivo obtido",
        "ano": "2026",
        "titulo": "Diagnosis and Management of Pseudomembranous Cystitis in Cat: A Case Report and Review of Literature",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler depois",
        "fichamento": "30 — Fichamento — Estresse em gatos domésticos ambiente urbano.md",
        "cautelas": "Conferir qualidade da fonte antes de usar como referência central.",
        "codigo": "30",
        "grupo": "Estresse, ambiente e comportamento felino",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Relaciona ambiente urbano, estresse crônico e saúde física/comportamental dos gatos.",
        "comoUsar": "Usar para justificar dados ambientais, rotina, enriquecimento, sinais de estresse e questionário do tutor.",
        "arquivo": "PDF/Síndrome CIF/Estresse+em+gatos+domésticos_+impacto+do+ambiente+urbano.EDITADO+..pdf",
        "referencia": "QUEIROZ, Beatriz Lopes; QUEIROZ, Hélio Lemes. Estresse em gatos domésticos: impacto do ambiente urbano na saúde física e comportamental. Revista ft, v. 30, n. 158, p. 01-23, 2026. DOI: 10.69849/y3zpv398.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Estresse em gatos domésticos: impacto do ambiente urbano na saúde física e comportamental",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "14 — Fichamento — Meow-Omni 1.md",
        "cautelas": "Cautela: arXiv/preprint e validação clínica ainda limitada.",
        "codigo": "14",
        "grupo": "IA multimodal e etologia felina",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "É o artigo mais próximo de uma ferramenta de IA voltada especificamente à interpretação multimodal do comportamento felino.",
        "comoUsar": "Usar como tendência/protótipo de IA multimodal para comportamento, sinais fisiológicos e apoio ao raciocínio veterinário.",
        "arquivo": "PDF/Síndrome CIF/Meow-Omni 1.pdf",
        "referencia": "HU, Jucheng et al. Meow-Omni 1: A Multimodal Large Language Model for Feline Ethology. [periodico NAO CONFIRMADO], 2026. Disponivel em: https://arxiv.org/pdf/2605.09152.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Meow-Omni 1: A Multimodal Large Language Model for Feline Ethology",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "1 — Fichamento — The Expanding Role of AI in Companion Animal Care.md",
        "cautelas": "Base de revisão sistemática; priorizar na conversa com o veterinário.",
        "codigo": "1",
        "grupo": "IA em animais de companhia",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão sistemática diretamente alinhada ao eixo da tese: IA em animais de companhia, comportamento, bem-estar e diagnóstico.",
        "comoUsar": "Usar para abrir o referencial de IA aplicada a cães/gatos e para justificar a lacuna em comportamento felino e monitoramento contínuo.",
        "arquivo": "PDF/Síndrome CIF/The Expanding Role of Artificial Intelligence in Companion.pdf",
        "referencia": "SABOLEK, Ivana; JOVIĆ, Alan. The Expanding Role of Artificial Intelligence in Companion Animal Care: A Systematic Review. Animals, v. 16, n. 7, p. 1035, 2026. DOI: 10.3390/ANI16071035/S1.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "The Expanding Role of Artificial Intelligence in Companion Animal Care: A Systematic Review",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S2 — Fichamento — MEMO in cats with idiopathic cystitis.md",
        "cautelas": "Ano 2006 aparece no nome do arquivo, nao foi confirmado no documento.",
        "codigo": "S2",
        "grupo": "Manejo ambiental multimodal (MEMO)",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Estudo classico que testa a modificacao ambiental multimodal como manejo da cistite idiopatica.",
        "comoUsar": "E a intervencao que fecha o argumento: se o ambiente causa, o ambiente tratado reduz o problema.",
        "arquivo": "PDF/Primordiais/buffington-et-al-2006-clinical-evaluation-of-multimodal-environmental-modification-(memo)-in-the-management-of-cats.pdf",
        "referencia": "BUFFINGTON, C. A. T. et al. Referencia completa NAO CONFIRMADA.",
        "status": "fichamento concluido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Clinical evaluation of multimodal environmental modification (MEMO) in the management of cats with idiopathic cystitis",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S6 — Fichamento — Feline Grimace Scale development and validation.md",
        "cautelas": "Ano, volume e paginacao NAO CONFIRMADOS (Scientific Reports).",
        "codigo": "S6",
        "grupo": "Avaliacao de dor por expressao facial",
        "tipoEstudo": "Estudo prospectivo caso-controle",
        "procedencia": "parcial - autoria confirmada no PDF, resto NAO CONFIRMADO",
        "porQueLer": "Desenvolve e valida a Feline Grimace Scale para detectar dor aguda por unidades de acao facial.",
        "comoUsar": "Unico instrumento validado de leitura de sinal clinico por imagem no acervo: ponte entre o Nucleo 1 e a captura por sensor/visao computacional.",
        "arquivo": "PDF/Síndrome CIF/Facial expressions of pain in cats.pdf",
        "referencia": "EVANGELISTA, M. C. et al. Scientific Reports. Referencia completa NAO CONFIRMADA.",
        "status": "fichamento concluido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Facial expressions of pain in cats: the development and validation of a Feline Grimace Scale",
        "nucleo": "Nucleo 2 - ambiente, comportamento e tecnologia"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N01",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/13_46.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N02",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S016815912600211X-main.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N03",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S0168169925005010-main.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N04",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S0940960226000178-main.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N05",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S2214180420301343-main.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N06",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/785661.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N07",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/A_FACETA_PSICOLOGICA_DA_CISTITE_INTERSTI.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N08",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/aalaf029.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N09",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/ajvr-ajvr.67.4.731.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N10",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/ANSIEDADE DE SEPARAÇÃO EM FELINOS DOMÉSTICOS.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N11",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Artigo01.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N12",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/biomolecules-16-00138-v2.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N13",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Cistite intersticial felina_01.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N14",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/defauw-et-al-2011-risk-factors-and-clinical-presentation-of-cats-with-feline-idiopathic-cystitis.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N15",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Diagnosticando_a_cistite_idiopatica_feli.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N16",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Doença do trato urinário inferior em felinos.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N17",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Exploring Viewer Perceptions of Videos Depicting Cat-Dissented  Play  and Their Potential to Contribute to Harmful Interactions.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N18",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/fvets-13-1727001.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N19",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/fvets-13-1780868.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N20",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/IFPB - Repositório Digital_ Manejo cat friendly_ implementação e avaliação em hospital veterinário sobre a percepção de médicos veterinários, graduandos e tutores.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N21",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Neurourology and Urodynamics - 2025 - Werneburg - Interstitial Cystitis Bladder Pain Syndrome  IC BPS  Diagnosis  Current.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N22",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Paper-Cistiteintersticial-Proclim-2016.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N23",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/ReginaldoPereira_Tese.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N24",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Serum and Urine Nerve Growth Factor and Glycosaminoglycan Levels in Obstructive and Non-Obstructive Feline Urolithiasis and Interstitial Cystitis.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N25",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Sindrome-de-Pandora-Muito-alem-da-cistite.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N26",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/The Role of Human-Cat Interactions in Shaping Domestic Cat.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N27",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Veterinary Medicine   Sci - 2026 - Maden - Serum and Urine Nerve Growth Factor and Glycosaminoglycan Levels in Obstructive.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N28",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/vetsci-13-00181.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N29",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/vfaf057.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N30",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Vista do Estresse em gatos domésticos.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    },
    {
        "fase": "A classificar",
        "fichamento": "nao iniciado",
        "cautelas": "Metadados não confirmados no documento original.",
        "codigo": "N31",
        "grupo": "NÃO CONFIRMADO",
        "tipoEstudo": "NÃO CONFIRMADO",
        "procedencia": "sem procedência",
        "porQueLer": "NÃO CONFIRMADO",
        "comoUsar": "NÃO CONFIRMADO",
        "arquivo": "PDF/Síndrome CIF/Vista do Síndrome de Pandora_ aspectos psiconeuroendócrinos.pdf",
        "referencia": "NÃO CONFIRMADO",
        "status": "arquivo obtido",
        "ano": "NÃO CONFIRMADO",
        "titulo": "NÃO CONFIRMADO",
        "nucleo": "NÃO CONFIRMADO"
    }
];
