window.DADOS_INVENTARIO = [
    {
        "fase": "Ler primeiro",
        "fichamento": "50 — Fichamento — Small adrenal glands in cats with FIC.md",
        "cautelas": "Essencial para a visão sistêmica da Pandora. Artigo antigo, mas muito importante.",
        "codigo": "50",
        "grupo": "Síndrome de Pandora e eixo neuroendócrino",
        "tipoEstudo": "Estudo experimental comparativo, com teste de estimulação por ACTH, dosagem de cortisol, análise morfométrica e avaliação histológica das glândulas adrenais de gatos saudáveis e gatos com cistite intersticial felina.",
        "procedencia": "preenchida por voce na triagem",
        "porQueLer": "Estudo clássico que relaciona alterações adrenais, eixo hipotálamo hipófise adrenal e cistite intersticial felina.",
        "comoUsar": "Usar como base neuroendócrina para discutir estresse, eixo HHA, adrenal e resposta fisiológica na Síndrome de Pandora.",
        "arquivo": "PDF/Primeiras Leituras/02_SMALL ADRENAL GLANDS IN CATS WITH FELINE INTERSTITIAL.pdf",
        "referencia": "WESTROPP, Jodi L.; WELK, Kristin A.; BUFFINGTON, C. A. Tony. Small adrenal glands in cats with feline interstitial cystitis. The Journal of Urology, v. 170, n. 6, p. 2494-2497, dez. 2003. DOI: 10.1097/01.ju.0000095566.63870.66.",
        "status": "fichamento concluido",
        "ano": "2003",
        "titulo": "Small adrenal glands in cats with feline interstitial cystitis",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler depois",
        "fichamento": "43 — Fichamento — Changing Paradigms of Feline Idiopathic Cystitis.md",
        "cautelas": "Artigo antigo; usar com revisões recentes.",
        "codigo": "43",
        "grupo": "Mudança de paradigma em FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Base conceitual para evolução histórica da compreensão da FIC.",
        "comoUsar": "Usar na introdução clínica/histórica.",
        "arquivo": "PDF/Síndrome CIF/Changing Paradigms.pdf",
        "referencia": "KRUGER, John M.; OSBORNE, Carl A.; LULICH, Jody P. Changing paradigms of feline idiopathic cystitis. Veterinary Clinics of North America: Small Animal Practice, v. 39, p. 15-40, 2008. DOI: 10.1016/j.cvsm.2008.09.008.",
        "status": "fichamento concluido",
        "ano": "2009",
        "titulo": "Changing Paradigms of Feline Idiopathic Cystitis",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "19 — Fichamento — Idiopathic Cystitis Beyond LUT.md",
        "cautelas": "Muito importante.",
        "codigo": "19",
        "grupo": "Síndrome de Pandora / além do trato urinário",
        "tipoEstudo": "revisao narrativa",
        "procedencia": "confirmada no PDF (26/09/2026)",
        "porQueLer": "Essencial para sustentar que o problema ultrapassa a bexiga e envolve estresse/sistema.",
        "comoUsar": "Usar para a transição FIC → Síndrome de Pandora e ferramenta sistêmica.",
        "arquivo": "PDF/Síndrome CIF/j.1939-1676.2011.0732.x.pdf",
        "referencia": "# 19 — Idiopathic cystitis in domestic cats—beyond the lower urinary tract\r\n\r\n**Referência ABNT ✔️ confirmada na fonte:**\r\nBUFFINGTON, C. A. T. Idiopathic cystitis in domestic cats—beyond the lower urinary tract. *Journal of Veterinary Internal Medicine*, v. 25, n. 4, p. 784–796, 2011. DOI: 10.1111/j.1939-1676.2011.0732.x\r\n\r\n**Tipo de estudo:** Revisão narrativa · **Autor:** C. A. Tony Buffington (Ohio State University) · **Periódico:** *J Vet Intern Med* · **Páginas:** 784–796\r\n\r\n**PDF:** `PDF_Para conhecimento\\j.1939-1676.2011.0732.x.pdf` — obtido em 26/09/2026 (antes: \"ainda não obtido\").\r\n\r\n**Fichamento:** [[19 — Fichamento — Idiopathic Cystitis Beyond LUT]]\r\n\r\n---\r\n\r\n## Resumo da função no acervo\r\n\r\nEste é o artigo em que o termo **\"Síndrome de Pandora\"** é proposto pela primeira vez (p. 785), como nome provisório para uma síndrome multissistêmica em gatos com sinais crônicos idiopáticos de TUI. O artigo propõe **três critérios provisórios** de diagnóstico (p. 785):\r\n\r\n1. Sinais em outros sistemas além do órgão principal.\r\n2. Flutuação dos sinais associada à ativação do SRS.\r\n3. Resolução com enriquecimento ambiental eficaz.\r\n\r\nO #51 (Buffington, Westropp e Chew, 2014) retoma o constructo e acrescenta o quarto critério (experiência adversa precoce).\r\n\r\n---\r\n\r\n[[00 Índice do cofre]] · [[Fila de leitura]] · [[MOC — Núcleo 1 (base histórica, clínica e fisiológica)]]",
        "status": "fichamento concluido",
        "ano": "2011",
        "titulo": "Idiopathic cystitis in domestic cats-beyond the lower urinary tract",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler depois",
        "fichamento": "34 — Fichamento — Risk factors and clinical presentation FIC.md",
        "cautelas": "Artigo antigo, mas específico.",
        "codigo": "34",
        "grupo": "Fatores de risco e apresentação clínica FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Fornece variáveis clínicas e fatores de risco para classificação/triagem.",
        "comoUsar": "Usar na definição de entradas clínicas e questionário.",
        "arquivo": "PDF/Síndrome CIF/defauw-et-al-2011-risk-factors-and-clinical-presentation-of-cats-with-feline-idiopathic-cystitis.pdf",
        "referencia": "DEFAUW, Pieter A. M. et al. Risk factors and clinical presentation of cats with feline idiopathic cystitis. Journal of Feline Medicine and Surgery, v. 13, n. 12, p. 967-975, 2011. DOI: 10.1016/j.jfms.2011.08.001.",
        "status": "fichamento concluido",
        "ano": "2011",
        "titulo": "Risk factors and clinical presentation of cats with feline idiopathic cystitis",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "51 — Fichamento — From FUS to Pandora syndrome.md",
        "cautelas": "Leitura obrigatória. Usar na introdução e justificativa.",
        "codigo": "51",
        "grupo": "Síndrome de Pandora e mudança conceitual",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Artigo central sobre a evolução conceitual de FUS e CIF para Síndrome de Pandora.",
        "comoUsar": "Usar como base conceitual principal para justificar que o foco da pesquisa deve ser Síndrome de Pandora, e não apenas cistite.",
        "arquivo": "PDF/Primordiais/tony-buffington-et-al-2014-from-fus-to-pandora-syndrome.pdf",
        "referencia": "BUFFINGTON, C. A. Tony; WESTROPP, Jodi L.; CHEW, Dennis J. From FUS to Pandora syndrome: where are we, how did we get here, and where to now? Journal of Feline Medicine and Surgery, v. 16, p. 385-394, 2014. DOI: 10.1177/1098612X14530212.",
        "status": "fichamento concluido",
        "ano": "2014",
        "titulo": "From FUS to Pandora syndrome: Where are we, how did we get here, and where to now?",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler depois",
        "fichamento": "40 — Fichamento — Feline Idiopathic Cystitis (VCNA 2015).md",
        "cautelas": "Artigo mais antigo, não substituir revisões recentes.",
        "codigo": "40",
        "grupo": "Revisão clínica FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão clínica útil para alinhamento com o veterinário.",
        "comoUsar": "Usar como apoio clínico, especialmente para linguagem veterinária.",
        "arquivo": "PDF/Síndrome CIF/Feline_idiopathic_cystitis_VCNA_2015.pdf",
        "referencia": "FORRESTER, S. Dru; TOWELL, Todd L. Feline idiopathic cystitis. Veterinary Clinics of North America: Small Animal Practice, v. 45, p. 783-806, 2015. DOI: 10.1016/j.cvsm.2015.02.007.",
        "status": "fichamento concluido",
        "ano": "2015",
        "titulo": "Feline Idiopathic Cystitis",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler depois",
        "fichamento": "29 — Fichamento — ISCAID bacterial UTI guidelines.md",
        "cautelas": "Diretriz clínica.",
        "codigo": "29",
        "grupo": "Diretriz ISCAID para ITU",
        "tipoEstudo": "diretriz clinica por consenso de especialistas",
        "procedencia": "confirmada no PDF (27/09/2026)",
        "porQueLer": "Importante para diferenciar infecção urinária bacteriana de FIC/Pandora.",
        "comoUsar": "Usar para critérios de exclusão, diagnóstico diferencial e segurança clínica.",
        "arquivo": "PDF/Síndrome CIF/13_46.pdf",
        "referencia": "WEESE, J. Scott et al. International Society for Companion Animal Infectious Diseases (ISCAID) guidelines for the diagnosis and management of bacterial urinary tract infections in dogs and cats. Veterinary Journal, v. 247, p. 8-25, 2019. DOI: 10.1016/j.tvjl.2019.02.008.",
        "status": "fichamento concluido",
        "ano": "2019",
        "titulo": "International Society for Companion Animal Infectious Diseases (ISCAID) guidelines for the diagnosis and management of bacterial urinary tract infections in dogs and cats",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "17 — Fichamento — FIC update review.md",
        "cautelas": "Essencial.",
        "codigo": "17",
        "grupo": "Revisão FIC: risco, biomarcadores e manejo",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Artigo guarda-chuva para FIC: prevalência, fatores de risco, biomarcadores e manejo.",
        "comoUsar": "Usar como base clínica principal para o problema-alvo.",
        "arquivo": "PDF/Síndrome CIF/Prevalence, Risk Factors,.pdf",
        "referencia": "HE, Chengxi; FAN, Kai; HAO, Zhihui; TANG, Na; LI, Gebin; WANG, Shuaiyu. Prevalence, risk factors, pathophysiology, potential biomarkers and management of feline idiopathic cystitis: an update review. Frontiers in Veterinary Science, v. 9, art. 900847, 2022. DOI: 10.3389/fvets.2022.900847.",
        "status": "fichamento concluido",
        "ano": "2022",
        "titulo": "Prevalence, Risk Factors, Pathophysiology, Potential Biomarkers and Management of Feline Idiopathic Cystitis: An Update Review",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler depois",
        "fichamento": "Modelo — Fichamento.md",
        "cautelas": "Contexto dos EUA. Ano vem do nome do arquivo, NAO CONFIRMADO no documento.",
        "codigo": "S9",
        "grupo": "Pratica clinica e conduta terapeutica",
        "tipoEstudo": "Survey",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Levantamento sobre como veterinarios nos EUA tratam FLUTD nao obstrutiva.",
        "comoUsar": "Mostra a distancia entre evidencia e pratica: util na justificativa de uma ferramenta de apoio.",
        "arquivo": "PDF/Síndrome CIF/krause-et-al-2024-survey-of-veterinarians-in-the-usa-to-evaluate-trends-in-the-treatment-approach-for-non-obstructive.pdf",
        "referencia": "KRAUSE et al. Referencia completa NAO CONFIRMADA.",
        "status": "arquivo obtido",
        "ano": "2024",
        "titulo": "Survey of veterinarians in the USA to evaluate trends in the treatment approach for non-obstructive FLUTD",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "26 — Fichamento — Urinary microbiome in healthy cats and FIC.md",
        "cautelas": "Verificar metadados, pois o título está traduzido.",
        "codigo": "26",
        "grupo": "Microbioma urinário e FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Conecta microbioma urinário, gatos saudáveis e FIC, útil para variáveis clínicas e discussão diagnóstica.",
        "comoUsar": "Usar em microbioma, exames complementares e limites da interpretação clínica.",
        "arquivo": "PDF/Síndrome CIF/Characterization and comparative.pdf",
        "referencia": "THASSAKORN, Patchaya et al. Characterization and comparative analysis of urinary bacterial microbiome profiling in healthy cats and cats with feline idiopathic cystitis. Scientific Reports, v. 16, n. 1, p. 4138, 2026.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Caracterização e análise comparativa do perfil do microbioma bacteriano urinário em gatos saudáveis e gatos com cistite idiopática felina.",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler depois",
        "fichamento": "41 — Fichamento — Low-dose RT for FIC in male cats.md",
        "cautelas": "Não é artigo de IA.",
        "codigo": "41",
        "grupo": "Tratamento e manejo de FIC/IC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Estudo clínico recente sobre terapia alternativa em casos graves de cistite idiopática/intersticial em gatos machos.",
        "comoUsar": "Usar apenas na discussão de possibilidades terapêuticas e limites da ferramenta de apoio à decisão.",
        "arquivo": "PDF/Síndrome CIF/aalaf029.pdf",
        "referencia": "KENDALL, Allison; VADEN, Shelly; GIEGER, Tracy; HARRIS, Tonya; GRUEN, Margaret E.; NOLAN, Michael W. Low-dose radiation therapy for idiopathic or interstitial cystitis in male cats. Journal of Veterinary Internal Medicine, v. 40, n. 1, art. aalaf029, p. 1-6, 2026. DOI: 10.1093/jvimsj/aalaf029.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Low-dose radiation therapy for idiopathic or interstitial cystitis in male cats",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "27 — Fichamento — Serum urine NGF GAG in FLUTD.md",
        "cautelas": "Artigo clínico, não IA.",
        "codigo": "27",
        "grupo": "Biomarcadores urinários e FLUTD",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Traz biomarcadores mensuráveis em urina/soro, úteis para pensar variáveis de entrada da ferramenta.",
        "comoUsar": "Usar em biomarcadores, classificação de risco e diferenciação entre FIC, urolitíase e obstrução.",
        "arquivo": "PDF/Síndrome CIF/Serum and Urine Nerve Growth Factor and Glycosaminoglycan Levels in Obstructive and Non‐Obstructive Feline Urolithiasis and Interstitial Cystitis.pdf",
        "referencia": "MADEN, Mehmet et al. Serum and Urine Nerve Growth Factor and Glycosaminoglycan Levels in Obstructive and Non-Obstructive Feline Urolithiasis and Interstitial Cystitis. Veterinary Medicine and Science, v. 12, n. 3, 2026. DOI: 10.1002/vms3.70968.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Serum and Urine Nerve Growth Factor and Glycosaminoglycan Levels in Obstructive and Non-Obstructive Feline Urolithiasis and Interstitial Cystitis",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S3 — Fichamento — External and internal influences on disease risk.md",
        "cautelas": "Secao \"Reference Point\" (JAVMA). Ano, volume e paginacao NAO CONFIRMADOS.",
        "codigo": "S3",
        "grupo": "Risco de doenca, ambiente e fisiologia",
        "tipoEstudo": "Artigo de revisao/posicionamento",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Texto de Buffington que articula influencias externas e internas sobre o risco de adoecer.",
        "comoUsar": "Ponte conceitual entre ambiente e fisiologia, anterior a formulacao da Sindrome de Pandora.",
        "arquivo": "PDF/Primordiais/External and internal influences.pdf",
        "referencia": "BUFFINGTON, C. A. Tony. External and internal influences on disease risk in cats. Journal of the American Veterinary Medical Association, v. 220, n. 7, p. 994-1002, 2002.",
        "status": "fichamento concluido",
        "ano": "NAO CONFIRMADO",
        "titulo": "External and internal influences on disease risk in cats",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "Modelo — Fichamento.md",
        "cautelas": "LITERATURA CINZENTA. Resumo de evento, sem revisao por pares. Ano NAO CONFIRMADO.",
        "codigo": "S8",
        "grupo": "Prevencao da Sindrome de Pandora",
        "tipoEstudo": "Resumo de evento",
        "procedencia": "parcial - evento confirmado no PDF, resto NAO CONFIRMADO",
        "porQueLer": "Resumo apresentado no XXVIII Simposio de Ciencias Aplicadas / VII Simposio Internacional da FAEF.",
        "comoUsar": "Uso restrito: eventualmente como registro de divulgacao em portugues, nunca como evidencia.",
        "arquivo": "PDF/Síndrome CIF/SÍNDROME DE PANDORA PREVENÇÃO.pdf",
        "referencia": "OLIVEIRA, V.; LEAL, R. Síndrome de Pandora: prevenção. [Título e demais dados NAO CONFIRMADOS]",
        "status": "fichamento concluido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Sindrome de Pandora: prevencao",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "Fichamentos/48 — Fichamento — Etiopathogenesis of Feline Idiopathic Cystitis.md",
        "cautelas": "ARQUIVO INCOMPLETO: o PDF tem 1 pagina apenas (pagina 435, inicio do capitulo 47). Obter o capitulo completo antes de fichar. Marca de composicao no rodape indica 2005.",
        "codigo": "48",
        "grupo": "Fisiopatologia da FIC",
        "tipoEstudo": "Capitulo de livro",
        "procedencia": "parcial - autoria, capitulo e ano confirmados no PDF; obra e paginacao final NAO CONFIRMADAS",
        "porQueLer": "Capítulo clássico sobre a etiopatogênese da cistite idiopática felina, abordando os mecanismos envolvidos na condição.",
        "comoUsar": "Usar como base clínica para explicar a etiopatogênese da CIF e sua relação com a Síndrome de Pandora.",
        "arquivo": "PDF/Síndrome CIF/ETIOPATHOGENESIS OF FELINE.pdf",
        "referencia": "WESTROPP, Jodi L.; BUFFINGTON, C. A. Tony. Etiopathogenesis of feline idiopathic cystitis. In: [OBRA NAO CONFIRMADA], cap. 47, p. 435-[final NAO CONFIRMADO], 2005.",
        "status": "fichamento concluido",
        "ano": "2005",
        "titulo": "Etiopathogenesis of Feline Idiopathic Cystitis",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler depois",
        "fichamento": "MOC — Núcleo 2 (ambiente, comportamento e tecnologia).md",
        "cautelas": "O fichamento desta fonte NAO esta nesta pasta, embora o acervo a registre como fichada.",
        "codigo": "S5",
        "grupo": "Fatores de risco comportamentais",
        "tipoEstudo": "Estudo retrospectivo",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Estudo retrospectivo de 336 gatos atendidos em clinica de comportamento em Barcelona.",
        "comoUsar": "Fornece fatores de risco comportamentais para cruzar com recorrencia da FIC.",
        "arquivo": "PDF/Primeiras Leituras/04_Potential risk factors associated with feline behaviour problems.pdf",
        "referencia": "AMAT, M. et al. Applied Animal Behaviour Science, v. 121, p. 134-139, 2009. DOI nao confirmado.",
        "status": "fichamento concluido",
        "ano": "2009",
        "titulo": "Potential risk factors associated with feline behaviour problems",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "53 — Fichamento — Sickness behaviors in response to unusual external events.md",
        "cautelas": "Essencial para Pandora, ambiente e comportamento. Não é artigo de IA.",
        "codigo": "53",
        "grupo": "Estresse, ambiente e comportamento",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Estudo observacional prospectivo que avaliou comportamentos de doença em resposta a eventos externos incomuns em gatos saudáveis e gatos com cistite intersticial felina.",
        "comoUsar": "Usar para justificar monitoramento ambiental, registro de eventos externos, rotina, comportamento do tutor e variáveis de estresse em ferramentas de IA.",
        "arquivo": "PDF/Síndrome CIF/Sickness behaviors in response.pdf",
        "referencia": "STELLA, Judi L.; LORD, Linda K.; BUFFINGTON, C. A. Tony. Sickness behaviors in response to unusual external events in healthy cats and cats with feline interstitial cystitis. Journal of the American Veterinary Medical Association, v. 238, n. 1, p. 67-73, 2011.",
        "status": "fichamento concluido",
        "ano": "2011",
        "titulo": "Sickness behaviors in response to unusual external events in healthy cats and cats with feline interstitial cystitis",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S4 — Fichamento — Stress in owned cats.md",
        "cautelas": "Ja fichada.",
        "codigo": "S4",
        "grupo": "Estresse e bem-estar em gatos domiciliados",
        "tipoEstudo": "Artigo de revisao",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Revisao sobre estressores do gato domiciliado e as mudancas comportamentais decorrentes.",
        "comoUsar": "Base do Nucleo 2 para definir estressores e sinais comportamentais mensuraveis.",
        "arquivo": "PDF/Primeiras Leituras/01_Stress in owned cats_behavioural.pdf",
        "referencia": "AMAT, Marta; CAMPS, Tomàs; MANTECA, Xavier. Stress in owned cats: behavioural changes and welfare implications. Journal of Feline Medicine and Surgery, v. 18, n. 8, p. 577-586, 2016. DOI: 10.1177/1098612X15590867.",
        "status": "fichamento concluido",
        "ano": "2016",
        "titulo": "Stress in owned cats: behavioural changes and welfare implications",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S1 — Fichamento — Social and environmental factors indoor cats.md",
        "cautelas": "Ja fichada. Revisao sistematica: conferir criterios de inclusao antes de generalizar.",
        "codigo": "S1",
        "grupo": "Ambiente e bem-estar de gatos de interior",
        "tipoEstudo": "Revisao sistematica",
        "procedencia": "confirmada na primeira pagina do PDF",
        "porQueLer": "Revisao sistematica que reune os fatores sociais e ambientais que afetam o bem-estar do gato de interior.",
        "comoUsar": "Sustenta o Nucleo 2: ambiente como determinante, e base para escolher o que monitorar.",
        "arquivo": "PDF/Primeiras Leituras/03_A systematic review of social and environmental factors.pdf",
        "referencia": "FOREMAN-WORSLEY, Rachel; FARNWORTH, Mark J. A systematic review of social and environmental factors and their implications for indoor cat welfare. Applied Animal Behaviour Science, v. 220, art. 104841, 2019. DOI: 10.1016/j.applanim.2019.104841.",
        "status": "fichamento concluido",
        "ano": "2019",
        "titulo": "A systematic review of social and environmental factors and their implications for indoor cat welfare",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler depois",
        "fichamento": "38 — Fichamento — Sensors big data and ML animal farming.md",
        "cautelas": "Cautela: não é animais de companhia.",
        "codigo": "38",
        "grupo": "Sensores, big data e ML em animais",
        "tipoEstudo": "Revisão de literatura (8 páginas)",
        "procedencia": "confirmada na fonte - autor (Neethirajan, Suresh), titulo, periodico, volume 29, artigo 100367, DOI verificados no PDF desta sessao (27/09/2026)",
        "porQueLer": "Apoia sensores, big data e machine learning, embora foque produção animal.",
        "comoUsar": "Usar como analogia tecnológica para coleta contínua e modelos preditivos.",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S2214180420301343-main.pdf",
        "referencia": "NEETHIRAJAN, Suresh. The role of sensors, big data and machine learning in modern animal farming. Sensing and Bio-Sensing Research, v. 29, art. 100367, 2020. DOI: 10.1016/j.sbsr.2020.100367.",
        "status": "fichamento concluido",
        "ano": "2020",
        "titulo": "The role of sensors, big data and machine learning in modern animal farming",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "Modelo — Fichamento.md",
        "cautelas": "Central para tese.",
        "codigo": "9",
        "grupo": "IA na prática clínica veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Discute aplicação potencial da IA na prática clínica e pesquisa biomédica veterinária.",
        "comoUsar": "Usar para conectar IA à rotina clínica e ao apoio ao veterinário.",
        "arquivo": "PDF/Síndrome CIF/The potential application of.pdf",
        "referencia": "AKINSULIE, Olalekan Chris et al. The potential application of artificial intelligence in veterinary clinical practice and biomedical research. Frontiers in Veterinary Science, v. 11, 2024. DOI: 10.3389/FVETS.2024.1347550.",
        "status": "fichamento concluido",
        "ano": "2024",
        "titulo": "The potential application of artificial intelligence in veterinary clinical practice and biomedical research",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "4 — Fichamento — Anna open-source platform ML classifiers EHR.md",
        "cautelas": "Muito forte para metodologia/proposta.",
        "codigo": "4",
        "grupo": "Ferramenta com prontuário veterinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Exemplo concreto de plataforma open-source integrando classificadores de ML ao prontuário eletrônico veterinário.",
        "comoUsar": "Usar como modelo de arquitetura para ferramenta de apoio à decisão.",
        "arquivo": "PDF/Síndrome CIF/Anna.pdf",
        "referencia": "KONG, Chun Yin et al. Anna: an open-source platform for real-time integration of machine learning classifiers with veterinary electronic health records. BMC Veterinary Research, v. 21, art. 557, 2025. DOI: 10.1186/s12917-025-05000-7.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Anna: an open-source platform for real-time integration of machine learning classifiers with veterinary electronic health records",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "Modelo — Fichamento.md",
        "cautelas": "Central para eixo de ferramentas.",
        "codigo": "3",
        "grupo": "Saúde digital de animais de companhia",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Conecta IA, saúde digital, tutores e animais de companhia.",
        "comoUsar": "Usar para justificar dados domiciliares, tutores, acompanhamento e medicina digital.",
        "arquivo": "PDF/Síndrome CIF/Artificial intelligence and companion animals.pdf",
        "referencia": "ARSHAD, Muhammad Furqan et al. Artificial intelligence and companion animals: Perspectives on digital healthcare for dogs, cats, and pet ownership. Research in Veterinary Science, v. 193, 2025. DOI: 10.1016/J. RVSC.2025.105776.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Artificial intelligence and companion animals: Perspectives on digital healthcare for dogs, cats, and pet ownership",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "7 — Fichamento — AI veterinary and animal science.md",
        "cautelas": "Central para tese.",
        "codigo": "7",
        "grupo": "IA veterinária: aplicações e desafios",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Panorama amplo e atual sobre aplicações, desafios e perspectivas da IA veterinária.",
        "comoUsar": "Usar na contextualização geral do campo e lacunas.",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S0168169925005010-main.pdf",
        "referencia": "HOSSEIN-ZADEH, Navid Ghavi. Artificial intelligence in veterinary and animal science: applications, challenges, and future prospects. Computers and Electronics in Agriculture, v. 235, 2025. DOI: 10.1016/J. COMPAG.2025.110395.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Artificial intelligence in veterinary and animal science: applications, challenges, and future prospects",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "2 — Fichamento — AI maturity in small animal veterinary medicine.md",
        "cautelas": "Muito importante para a tese.",
        "codigo": "2",
        "grupo": "Maturidade da IA em pequenos animais",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Explica que a IA já cria valor em algumas áreas e ainda é imatura em outras.",
        "comoUsar": "Usar para justificar ferramentas inexistentes ou em estágio experimental.",
        "arquivo": "PDF/Síndrome CIF/Artificial intelligence is beginning to create value for selected.pdf",
        "referencia": "ALBERGANTE, Luca; O’FLYNN, Ciaran; DE MEYER, Geert. Artificial intelligence is beginning to create value for selected small animal veterinary applications while remaining immature for others. Journal of the American Veterinary Medical Association, v. 263, n. 3, p. 388-394, 2025. DOI: 10.2460/JAVMA.24.09.0617.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Artificial intelligence is beginning to create value for selected small animal veterinary applications while remaining immature for others",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "49 — Fichamento — Behavioral factors and recurrence in FIC.md",
        "cautelas": "Muito forte para a tese. Artigo clínico/comportamental, não de IA.",
        "codigo": "49",
        "grupo": "Estresse, comportamento e recorrência",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Investiga associação entre fatores comportamentais, medo, ansiedade e recorrência da CIF em gatos.",
        "comoUsar": "Usar para justificar questionários do tutor, monitoramento comportamental, previsão de recorrência e variáveis comportamentais em ferramentas de IA.",
        "arquivo": "PDF/Síndrome CIF/Association between behavioral factors and recurrence rate in cats with.pdf",
        "referencia": "CAUDRON, Marianne; LAROCHE, Pascale; BAZIN, Isabelle; DESMARCHELIER, Marion. Association between behavioral factors and recurrence rate in cats with feline \"idiopathic\" cystitis. Journal of Veterinary Behavior, v. 78, p. 90-96, 2025. DOI: 10.1016/j.jveb.2025.02.005.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Association between behavioral factors and recurrence rate in cats with feline “idiopathic” cystitis",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "Modelo — Fichamento.md",
        "cautelas": "Central para ferramentas.",
        "codigo": "5",
        "grupo": "Sensores e sinais vitais remotos",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Base tecnológica para monitoramento remoto, sinais vitais e coleta de dados clínicos.",
        "comoUsar": "Usar para justificar sensores, telemetria e monitoramento domiciliar ou clínico.",
        "arquivo": "PDF/Síndrome CIF/Remote Vital Sensing in Clinical Veterinary Medicine.pdf",
        "referencia": "ZHAO, Xinyue et al. Remote vital sensing in clinical veterinary medicine: a comprehensive review of recent advances, accomplishments, challenges, and future perspectives. Animals, v. 15, art. 1033, 2025. DOI: 10.3390/ani15071033.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Remote Vital Sensing in Clinical Veterinary Medicine: A Comprehensive Review of Recent Advances, Accomplishments, Challenges, and Future Perspectives",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "6 — Fichamento — Deep learning in veterinary diagnostics.md",
        "cautelas": "Central para IA.",
        "codigo": "6",
        "grupo": "Deep learning em diagnóstico veterinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão central sobre deep learning em diagnóstico veterinário e saúde animal.",
        "comoUsar": "Usar na base metodológica de IA, tipos de dados e modelos.",
        "arquivo": "PDF/Síndrome CIF/Review of applications of deep.pdf",
        "referencia": "XIAO, Sam; DHAND, Navneet K.; WANG, Zhiyong; HU, Kun; THOMSON, Peter C.; HOUSE, John K.; KHATKAR, Mehar S. Review of applications of deep learning in veterinary diagnostics and animal health. Frontiers in Veterinary Science, v. 12, art. 1511522, 2025. DOI: 10.3389/fvets.2025.1511522.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Review of applications of deep learning in veterinary diagnostics and animal health",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "16 — Fichamento — Evidence base management of recurrent FIC.md",
        "cautelas": "Central para base clínica.",
        "codigo": "16",
        "grupo": "Manejo baseado em evidências da FIC",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão sistemática sobre estratégias de manejo de FIC recorrente.",
        "comoUsar": "Usar para separar recomendações fortes, fracas e lacunas que a ferramenta pode apoiar.",
        "arquivo": "PDF/Síndrome CIF/Understanding_the_current_evidence_base_for_the_commonly_recommended_management_strategies_for_recurrent_feline_idiopath.pdf",
        "referencia": "MACLEOD, B.; LAVEN, L. J.; LAVEN, R. A.; HILL, K. E. Understanding the current evidence base for the commonly recommended management strategies for recurrent feline idiopathic cystitis: a systematic review. New Zealand Veterinary Journal, v. 73, n. 4, p. 233-245, 2025. DOI: 10.1080/00480169.2025.2477542.",
        "status": "fichamento concluido",
        "ano": "2025",
        "titulo": "Understanding the current evidence base for the commonly recommended management strategies for recurrent feline idiopathic cystitis: a systematic review",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler depois",
        "fichamento": "25 — Fichamento — Advanced precision veterinary technologies smart boluses.md",
        "cautelas": "Mais amplo que gatos/FIC.",
        "codigo": "25",
        "grupo": "Tecnologias inteligentes e monitoramento",
        "tipoEstudo": "revisao narrativa",
        "procedencia": "confirmada no PDF (26/09/2026)",
        "porQueLer": "Apoia a discussão sobre dispositivos inteligentes, monitoramento e tecnologias veterinárias de precisão.",
        "comoUsar": "Usar como base tecnológica complementar para sensores e coleta contínua.",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S1773224725009669-main.pdf",
        "referencia": "JHILTA, Agrim; JADHAV, Krishna; SINGH, Raghuraj; NEGI, Swarnima; KAUR, Shaguneet; SHARMA, Neelesh; VERMA, Rahul Kumar. Advanced precision veterinary technologies and smart boluses: Innovations in drug delivery, health monitoring, and future perspectives. Journal of Drug Delivery Science and Technology, v. 115, artigo 107563, 2026. DOI: 10.1016/j.jddst.2025.107563.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Advanced precision veterinary technologies and smart boluses: Innovations in drug delivery, health monitoring, and future perspectives",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler com cautela",
        "fichamento": "Modelo — Fichamento.md",
        "cautelas": "Cautela: preprint/relato de caso; não usar como base central.",
        "codigo": "47",
        "grupo": "Diagnóstico diferencial urinário",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Relato/revisão sobre cistite pseudomembranosa; útil para diferencial, mas não representa FIC/Pandora.",
        "comoUsar": "Usar para mostrar que a ferramenta deve evitar classificar toda cistite como FIC.",
        "arquivo": "PDF/Síndrome CIF/Diagnosis_and_Management_of.pdf",
        "referencia": "SHI, Qian et al. Diagnosis and Management of Pseudomembranous Cystitis in Cat: A Case Report and Review of Literature. [periodico NAO CONFIRMADO], 2026. DOI: 10.20944/preprints202605.0381.v1.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Diagnosis and Management of Pseudomembranous Cystitis in Cat: A Case Report and Review of Literature",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler depois",
        "fichamento": "Fichamentos/30 — Fichamento — Estresse em gatos domésticos ambiente urbano.md",
        "cautelas": "Conferir qualidade da fonte antes de usar como referência central.",
        "codigo": "30",
        "grupo": "Estresse, ambiente e comportamento felino",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Relaciona ambiente urbano, estresse crônico e saúde física/comportamental dos gatos.",
        "comoUsar": "Usar para justificar dados ambientais, rotina, enriquecimento, sinais de estresse e questionário do tutor.",
        "arquivo": "PDF/Síndrome CIF/Estresse+em+gatos+domésticos_+impacto+do+ambiente+urbano.EDITADO+..pdf",
        "referencia": "QUEIROZ, Beatriz Lopes; QUEIROZ, Hélio Lemes. Estresse em gatos domésticos: impacto do ambiente urbano na saúde física e comportamental. Revista ft, v. 30, n. 158, p. 01-23, 2026. DOI: 10.69849/y3zpv398.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Estresse em gatos domésticos: impacto do ambiente urbano na saúde física e comportamental",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "11 — Fichamento — Ethical AI veterinary decisions.md",
        "cautelas": "Central para segurança e responsabilidade.",
        "codigo": "11",
        "grupo": "Ética e tomada de decisão veterinária",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Diretamente ligado à tomada de decisão veterinária com IA.",
        "comoUsar": "Usar para delimitar que a ferramenta auxilia, mas não substitui o veterinário.",
        "arquivo": "PDF/Síndrome CIF/fvets-13-1780868.pdf",
        "referencia": "HEINLEIN, Matt. Ethical considerations of artificial intelligence in veterinary medicine decision-making. Frontiers in Veterinary Science, v. 13, 2026. DOI: 10.3389/FVETS.2026.1780868.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Ethical considerations of artificial intelligence in veterinary medicine decision-making",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "14 — Fichamento — Meow-Omni 1.md",
        "cautelas": "Cautela: arXiv/preprint e validação clínica ainda limitada.",
        "codigo": "14",
        "grupo": "IA multimodal e etologia felina",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "É o artigo mais próximo de uma ferramenta de IA voltada especificamente à interpretação multimodal do comportamento felino.",
        "comoUsar": "Usar como tendência/protótipo de IA multimodal para comportamento, sinais fisiológicos e apoio ao raciocínio veterinário.",
        "arquivo": "PDF/Síndrome CIF/Meow-Omni 1.pdf",
        "referencia": "HU, Jucheng et al. Meow-Omni 1: a multimodal large language model for feline ethology. arXiv:2605.09152v1 [cs.CL], 9 maio 2026. Preprint.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "Meow-Omni 1: A Multimodal Large Language Model for Feline Ethology",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "Fichamentos/1 — Fichamento — The Expanding Role of AI in Companion Animal Care.md",
        "cautelas": "Base de revisão sistemática; priorizar na conversa com o veterinário.",
        "codigo": "1",
        "grupo": "IA em animais de companhia",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Revisão sistemática diretamente alinhada ao eixo da tese: IA em animais de companhia, comportamento, bem-estar e diagnóstico.",
        "comoUsar": "Usar para abrir o referencial de IA aplicada a cães/gatos e para justificar a lacuna em comportamento felino e monitoramento contínuo.",
        "arquivo": "PDF/Síndrome CIF/The Expanding Role of Artificial Intelligence in Companion.pdf",
        "referencia": "SABOLEK, Ivana; JOVIĆ, Alan. The Expanding Role of Artificial Intelligence in Companion Animal Care: A Systematic Review. Animals, v. 16, n. 7, p. 1035, 2026. DOI: 10.3390/ANI16071035/S1.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "The Expanding Role of Artificial Intelligence in Companion Animal Care: A Systematic Review",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler depois",
        "fichamento": "20 — Fichamento — AI adoption paradox China.md",
        "cautelas": "Contexto geográfico específico: China.",
        "codigo": "20",
        "grupo": "Adoção de IA por veterinários",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "gerada do .bib - CONFERIR no artigo",
        "porQueLer": "Mostra adoção elevada com baixa familiaridade, importante para discutir barreiras reais de implementação.",
        "comoUsar": "Usar na discussão sobre confiança, treinamento e interface das ferramentas de IA.",
        "arquivo": "PDF/Síndrome CIF/fvets-13-1727001.pdf",
        "referencia": "LI, Shumin; LAI, Xiaoyun. The adoption paradox for veterinary professionals in China: high use of artificial intelligence despite low familiarity. Frontiers in Veterinary Science, v. 13, 2026. DOI: 10.3389/fvets.2026.1727001.",
        "status": "fichamento concluido",
        "ano": "2026",
        "titulo": "The adoption paradox for veterinary professionals in China: high use of artificial intelligence despite low familiarity",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S2 — Fichamento — MEMO in cats with idiopathic cystitis.md",
        "cautelas": "Ano 2006 aparece no nome do arquivo, nao foi confirmado no documento.",
        "codigo": "S2",
        "grupo": "Manejo ambiental multimodal (MEMO)",
        "tipoEstudo": "NAO CONFIRMADO",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Estudo classico que testa a modificacao ambiental multimodal como manejo da cistite idiopatica.",
        "comoUsar": "E a intervencao que fecha o argumento: se o ambiente causa, o ambiente tratado reduz o problema.",
        "arquivo": "PDF/Primordiais/buffington-et-al-2006-clinical-evaluation-of-multimodal-environmental-modification-(memo)-in-the-management-of-cats.pdf",
        "referencia": "BUFFINGTON, C. A. Tony; WESTROPP, Jodi L.; CHEW, Dennis J.; BOLUS, Roger R. Clinical evaluation of multimodal environmental modification (MEMO) in the management of cats with idiopathic cystitis. Journal of Feline Medicine and Surgery, v. 8, p. 261-268, 2006. DOI: 10.1016/j.jfms.2006.02.002.",
        "status": "fichamento concluido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Clinical evaluation of multimodal environmental modification (MEMO) in the management of cats with idiopathic cystitis",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "S6 — Fichamento — Feline Grimace Scale development and validation.md",
        "cautelas": "Ano, volume e paginacao NAO CONFIRMADOS (Scientific Reports).",
        "codigo": "S6",
        "grupo": "Avaliacao de dor por expressao facial",
        "tipoEstudo": "Estudo prospectivo caso-controle",
        "procedencia": "parcial - autoria confirmada no PDF, resto NAO CONFIRMADO",
        "porQueLer": "Desenvolve e valida a Feline Grimace Scale para detectar dor aguda por unidades de acao facial.",
        "comoUsar": "Unico instrumento validado de leitura de sinal clinico por imagem no acervo: ponte entre o Nucleo 1 e a captura por sensor/visao computacional.",
        "arquivo": "PDF/Síndrome CIF/Facial expressions of pain in cats.pdf",
        "referencia": "EVANGELISTA, Marina C. et al. Facial expressions of pain in cats: the development and validation of a Feline Grimace Scale. Scientific Reports, v. 9, art. 19128, 2019. DOI: 10.1038/s41598-019-55693-8.",
        "status": "fichamento concluido",
        "ano": "NAO CONFIRMADO",
        "titulo": "Facial expressions of pain in cats: the development and validation of a Feline Grimace Scale",
        "nucleo": "Núcleo 2"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "Fichamentos/54 — Fichamento — Effects of stress in cats with FIC.md",
        "cautelas": "",
        "codigo": "54",
        "grupo": "Fisiopatologia da FIC",
        "tipoEstudo": "Artigo original — estudo prospectivo experimental",
        "procedencia": "confirmada no PDF - autores, titulo, periodico, volume, numero, paginas e ano",
        "porQueLer": "Estudo prospectivo controlado (laboratorio) que documenta permeabilidade vesical aumentada e ativacao do SNS em gatos com FIC expostos a estresse moderado, com melhora apos enriquecimento ambiental. Base fisiologica do MEMO (S2) e do achado de adrenais menores (#50).",
        "comoUsar": "Evidencia experimental que une estresse ambiental -> ativacao do SNS -> sinais urinarios em gatos com FIC. Suporta o manejo ambiental como intervencao terapeutica e documenta a dissociacao SNS-elevado/cortisol-normal, confirmando insuficiencia adrenocortical relativa de #50.",
        "arquivo": "PDF/Síndrome CIF/ajvr-ajvr.67.4.731.pdf",
        "referencia": "WESTROPP, Jodi L.; KASS, Philip H.; BUFFINGTON, C. A. T. Evaluation of the effects of stress in cats with idiopathic cystitis. American Journal of Veterinary Research, v. 67, n. 4, p. 731–736, abr. 2006.",
        "status": "fichamento concluido",
        "ano": "2006",
        "titulo": "Evaluation of the effects of stress in cats with idiopathic cystitis",
        "nucleo": "Núcleo 1"
    },
    {
        "fase": "Ler primeiro",
        "fichamento": "",
        "cautelas": "Sensors and Materials e revista de menor impacto; verificar indexacao e fator de impacto; abordagem cross-species pode mascarar limitacoes especificas para gatos.",
        "codigo": "57",
        "grupo": "Sensor IMU e DL cross-species (gatos e caes)",
        "tipoEstudo": "Estudo experimental (DL + sensor)",
        "procedencia": "confirmada no PDF original: primeira pagina, DOI 10.18494/SAM5359",
        "porQueLer": "CNN+LSTM com dados de IMU para reconhecimento de comportamento em gatos e caes",
        "comoUsar": "89% de precisao em gatos confirmada na revisao #1",
        "arquivo": "PDF/Síndrome CIF/Cat and Dog Behavior Recognition IMU.pdf",
        "referencia": "CHEN, Guanyu et al. Cat and Dog Behavior Recognition Method Using Deep Learning Approach Based on Inertial Measurement Unit Sensor Data. Sensors and Materials, v. 37, n. 3, p. 1073–1098, 2025. DOI: 10.18494/SAM5359. Referência confirmada na primeira página do PDF original; “Part 3” NÃO CONFIRMADO no documento.",
        "status": "arquivo obtido",
        "ano": "2025",
        "titulo": "Cat and Dog Behavior Recognition Method Using Deep Learning Approach Based on Inertial Measurement Unit Sensor Data",
        "nucleo": "Núcleo 2"
    },
    {
        "codigo": "N02",
        "titulo": "Owner-reported experiences of transitioning cats from outdoor to indoor living",
        "ano": "2026",
        "nucleo": "Núcleo 2",
        "fase": "Ler depois",
        "status": "fichamento concluido",
        "grupo": "Transição de gatos para vida exclusivamente interna",
        "tipoEstudo": "estudo transversal retrospectivo por questionário",
        "procedencia": "adendo ao inventário — PDF identificado em 27/09/2026",
        "porQueLer": "",
        "comoUsar": "",
        "cautelas": "",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S016815912600211X-main.pdf",
        "referencia": "HENNING, Julia S. L.; MCDONALD, Nicola; ZOBEL, Gosia; RAILTON, Renee; WARAN, Natalie; HAZEL, Susan J. Owner-reported experiences of transitioning cats from outdoor to indoor living. Applied Animal Behaviour Science, v. 304, art. 107120, 2026. DOI: 10.1016/j.applanim.2026.107120."
    },
    {
        "codigo": "N04",
        "titulo": "Artificial intelligence in animal anatomy: Exploring the technologies, applications, benefits, and challenges",
        "ano": "2026",
        "nucleo": "Núcleo 2",
        "fase": "Ler com cautela",
        "status": "fichamento concluido",
        "grupo": "IA aplicada à anatomia animal",
        "tipoEstudo": "revisão narrativa",
        "procedencia": "adendo ao inventário — PDF identificado em 27/09/2026",
        "porQueLer": "",
        "comoUsar": "",
        "cautelas": "",
        "arquivo": "PDF/Síndrome CIF/1-s2.0-S0940960226000178-main.pdf",
        "referencia": "NAO CONFIRMADO"
    },
    {
        "codigo": "N07",
        "titulo": "A faceta psicológica da cistite intersticial dos gatos domésticos",
        "ano": "2013",
        "nucleo": "Núcleo 2",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Faceta psicológica da cistite intersticial",
        "tipoEstudo": "TCC de especialização — revisão narrativa",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Fundamentação ambiental e comportamental da FIC.",
        "comoUsar": "",
        "cautelas": "Literatura cinzenta; PDF fragmentário (pp. 9–29); método de busca NÃO CONFIRMADO.",
        "arquivo": "PDF/Síndrome CIF/A_FACETA_PSICOLOGICA_DA_CISTITE_INTERSTI.pdf",
        "referencia": "ENGLES, F. S. A faceta psicológica da cistite intersticial dos gatos domésticos. 2013. Trabalho de Conclusão de Curso (Especialização) — Equalis, Curitiba, 2013. Demais elementos: NÃO CONFIRMADO."
    },
    {
        "codigo": "N11",
        "titulo": "Análise Comparativa de Modelos Estatísticos e Redes Neurais na Detecção de Cistite a partir de Dados Clínicos",
        "ano": "NÃO CONFIRMADO",
        "nucleo": "Núcleo 2",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Análise comparativa de modelos para cistite",
        "tipoEstudo": "estudo computacional comparativo",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Metodologia e justificativa tecnológica; exemplo de comparação de modelos, não evidência clínica para FIC.",
        "comoUsar": "",
        "cautelas": "Fonte sem dados editoriais confirmáveis no PDF; doença e população humanas; dataset público pequeno e pertinência clínica felina indireta.",
        "arquivo": "PDF/Síndrome CIF/Artigo01.pdf",
        "referencia": "BRITO, Rhyan Ximenes de; XIMENES, Janaide Nogueira de Sousa. Análise Comparativa de Modelos Estatísticos e Redes Neurais na Detecção de Cistite a partir de Dados Clínicos. Periódico, volume, número, páginas, ano e DOI: NÃO CONFIRMADO."
    },
    {
        "codigo": "N12",
        "titulo": "Advances in Cytokines and Inflammatory Mechanisms in the Pathogenesis of Interstitial Cystitis/Bladder Pain Syndrome",
        "ano": "2026",
        "nucleo": "Núcleo 1",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Citocinas e inflamação em IC BPS",
        "tipoEstudo": "revisão narrativa",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Fundamentação fisiopatológica comparada, com cautela explícita sobre espécie.",
        "comoUsar": "",
        "cautelas": "Foco humano; revisão sem método sistemático declarado; extrapolação para gatos exige fontes primárias felinas.",
        "arquivo": "PDF/Síndrome CIF/biomolecules-16-00138-v2.pdf",
        "referencia": "XIAO, Yulin; ZHU, Donglin; ZHOU, Xiangfu. Advances in Cytokines and Inflammatory Mechanisms in the Pathogenesis of Interstitial Cystitis/Bladder Pain Syndrome. Biomolecules, v. 16, n. 1, art. 138, 2026. DOI: 10.3390/biom16010138."
    },
    {
        "codigo": "N13",
        "titulo": "Semelhanças entre a doença idiopática do trato urinário inferior dos felinos e a cistite intersticial humana",
        "ano": "2004",
        "nucleo": "Núcleo 1",
        "fase": "Ler primeiro",
        "status": "fichamento concluido",
        "grupo": "Comparação clínica e fisiopatológica entre DITUIF e cistite intersticial humana",
        "tipoEstudo": "revisão bibliográfica",
        "procedencia": "adendo ao inventário — PDF identificado em 27/09/2026",
        "porQueLer": "",
        "comoUsar": "",
        "cautelas": "",
        "arquivo": "PDF/Síndrome CIF/Cistite intersticial felina_01.pdf",
        "referencia": "NAO CONFIRMADO"
    },
    {
        "codigo": "N15",
        "titulo": "Diagnosticando a cistite idiopática felina: Revisão",
        "ano": "2017",
        "nucleo": "Núcleo 1",
        "fase": "Ler primeiro",
        "status": "fichamento concluido",
        "grupo": "Diagnóstico, fisiopatologia e manejo da cistite idiopática felina",
        "tipoEstudo": "revisão",
        "procedencia": "adendo ao inventário — PDF identificado em 27/09/2026",
        "porQueLer": "",
        "comoUsar": "",
        "cautelas": "",
        "arquivo": "PDF/Síndrome CIF/Diagnosticando_a_cistite_idiopatica_feli.pdf",
        "referencia": "NAO CONFIRMADO"
    },
    {
        "codigo": "N16",
        "titulo": "Doença do Trato Urinário Inferior em Felinos: Revisão Bibliográfica e Relato de um Caso Clínico de Obstrução Uretral",
        "ano": "2026",
        "nucleo": "Núcleo 1",
        "fase": "A classificar",
        "status": "fichamento parcial - previa",
        "grupo": "DTUIF revisão e caso de obstrução",
        "tipoEstudo": "relatório de estágio — prévia",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Contexto clínico de DTUIF; não usar dados não visíveis na prévia.",
        "comoUsar": "",
        "cautelas": "Arquivo é PREVIEW incompleto; resultados, discussão e conclusão integrais não estão disponíveis. Fichamento necessariamente parcial.",
        "arquivo": "PDF/Síndrome CIF/Doença do trato urinário inferior em felinos.pdf",
        "referencia": "LEAL, Júlia Aidos. Doença do Trato Urinário Inferior em Felinos: Revisão Bibliográfica e Relato de um Caso Clínico de Obstrução Uretral. 2026. Relatório de Estágio (Mestrado Integrado em Medicina Veterinária) — Universidade de Évora, Évora, 2026."
    },
    {
        "codigo": "N17",
        "titulo": "Exploring Viewer Perceptions of Videos Depicting Cat-Dissented “Play” and Their Potential to Contribute to Harmful Interactions",
        "ano": "2026",
        "nucleo": "Núcleo 2",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Percepções de brincadeira recusada por gatos",
        "tipoEstudo": "estudo qualitativo de conteúdo on-line",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Fundamentação de interação gato–humano e desenho de alertas comportamentais.",
        "comoUsar": "",
        "cautelas": "Amostra de plataforma e seleção intencional; comentários não representam tutores em geral; inferências qualitativas.",
        "arquivo": "PDF/Síndrome CIF/Exploring Viewer Perceptions of Videos Depicting Cat-Dissented  Play  and Their Potential to Contribute to Harmful Interactions.pdf",
        "referencia": "HENNING, Julia Sophie Lyn; NIELSEN, Torben Dahl; HAZEL, Susan Jane. Exploring Viewer Perceptions of Videos Depicting Cat-Dissented “Play” and Their Potential to Contribute to Harmful Interactions. Anthrozoös, v. 39, n. 5, p. 1015–1039, 2026. DOI: 10.1080/08927936.2026.2708478."
    },
    {
        "codigo": "N20",
        "titulo": "Manejo Cat Friendly: implementação e avaliação em hospital veterinário sobre a percepção de médicos veterinários, graduandos e tutores",
        "ano": "2026",
        "nucleo": "Núcleo 2",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Manejo Cat Friendly em hospital veterinário",
        "tipoEstudo": "TCC com intervenção e questionários de percepção",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Fundamentação ambiental e metodológica para avaliação de aceitabilidade de intervenções.",
        "comoUsar": "",
        "cautelas": "Literatura cinzenta, único hospital, medidas de percepção e amostra de conveniência; não avalia FIC diretamente.",
        "arquivo": "PDF/Síndrome CIF/IFPB - Repositório Digital_ Manejo cat friendly_ implementação e avaliação em hospital veterinário sobre a percepção de médicos veterinários, graduandos e tutores.pdf",
        "referencia": "SILVA, Thayline Holanda da. Manejo Cat Friendly: implementação e avaliação em hospital veterinário sobre a percepção de médicos veterinários, graduandos e tutores. 2026. 50 f. Trabalho de Conclusão de Curso (Bacharelado em Medicina Veterinária) — Instituto Federal da Paraíba, Sousa, 2026."
    },
    {
        "codigo": "N21",
        "titulo": "Interstitial Cystitis/Bladder Pain Syndrome (IC/BPS) Diagnosis: Current Limitations and a Pragmatic Clinical Diagnostic Definition",
        "ano": "2026",
        "nucleo": "Núcleo 1",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Diagnóstico pragmático de IC BPS",
        "tipoEstudo": "consenso de especialistas",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Comparação conceitual e histórica do diagnóstico por exclusão.",
        "comoUsar": "",
        "cautelas": "Consenso humano, não estudo veterinário; critérios não podem ser transplantados para gatos.",
        "arquivo": "PDF/Síndrome CIF/Neurourology and Urodynamics - 2025 - Werneburg - Interstitial Cystitis Bladder Pain Syndrome  IC BPS  Diagnosis  Current.pdf",
        "referencia": "WERNEBURG, Glenn T. et al. Interstitial Cystitis/Bladder Pain Syndrome (IC/BPS) Diagnosis: Current Limitations and a Pragmatic Clinical Diagnostic Definition. Neurourology and Urodynamics, v. 45, n. 1, p. 32–38, 2026. DOI: 10.1002/nau.70112."
    },
    {
        "codigo": "N22",
        "titulo": "Cistite intersticial",
        "ano": "2016",
        "nucleo": "Núcleo 1",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Cistite intersticial humana PROCLIM",
        "tipoEstudo": "capítulo de educação continuada",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Comparação histórica e fisiopatológica humano–felino.",
        "comoUsar": "",
        "cautelas": "Fonte humana e de educação continuada; não é revisão sistemática nem evidência felina.",
        "arquivo": "PDF/Síndrome CIF/Paper-Cistiteintersticial-Proclim-2016.pdf",
        "referencia": "FACIO JUNIOR, Fernando Nestor; VASILCEAC, Fábio Augusto; GABRIOTTI, Luis Francisco Barbero; SPESSOTO, Luis Cesar Fava. Cistite intersticial. In: SOCIEDADE BRASILEIRA DE CLÍNICA MÉDICA; LOPES, A. C.; CIPULLO, J. P.; KUBIAK, C. A. P. (org.). PROCLIM: Programa de Atualização em Clínica Médica, Ciclo 13, v. 3. Porto Alegre: Artmed Panamericana, 2016. p. 67–79."
    },
    {
        "codigo": "N23",
        "titulo": "Parâmetros clínicos e biomarcadores sistêmicos e teciduais da resposta inflamatória em gatos com perda da integridade das mucosas oral, intestinal e uretral",
        "ano": "2020",
        "nucleo": "Núcleo 1",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Biomarcadores inflamatórios em gatos",
        "tipoEstudo": "tese de doutorado — quatro protocolos",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Biomarcadores e complicações clínicas, com delimitação da população.",
        "comoUsar": "",
        "cautelas": "Tese multitemática; bloco urinário é pós-uretrostomia e não equivale a FIC/Pandora; grupos pequenos, sobretudo PPU.",
        "arquivo": "PDF/Síndrome CIF/ReginaldoPereira_Tese.pdf",
        "referencia": "SOUSA FILHO, Reginaldo Pereira de. Parâmetros clínicos e biomarcadores sistêmicos e teciduais da resposta inflamatória em gatos com perda da integridade das mucosas oral, intestinal e uretral. 2020. 135 f. Tese (Doutorado em Ciências Veterinárias) — Universidade Estadual do Ceará, Fortaleza, 2020."
    },
    {
        "codigo": "N25",
        "titulo": "Síndrome de Pandora: Muito Além da Cistite",
        "ano": "2020",
        "nucleo": "Núcleo 1",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Síndrome de Pandora muito além da cistite",
        "tipoEstudo": "informativo técnico — revisão narrativa",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Introdução didática à Síndrome de Pandora; confirmar afirmações nas fontes primárias citadas.",
        "comoUsar": "",
        "cautelas": "Informativo técnico, não estudo primário; método de busca e revisão por pares NÃO CONFIRMADOS.",
        "arquivo": "PDF/Síndrome CIF/Sindrome-de-Pandora-Muito-alem-da-cistite.pdf",
        "referencia": "DEL BARRIO, Maria Alessandra Martins; MAZZIERO, Victória Gardinal. Síndrome de Pandora: Muito Além da Cistite. PremieRvet — Informativo Técnico, ed. I/2020, 2020. Volume, número e páginas editoriais: NÃO CONFIRMADO."
    },
    {
        "codigo": "N26",
        "titulo": "The Role of Human-Cat Interactions in Shaping Domestic Cat (Felis catus) Hunting Behavior",
        "ano": "2026",
        "nucleo": "Núcleo 2",
        "fase": "A classificar",
        "status": "fichamento parcial - previa",
        "grupo": "Interações humano gato e caça — prévia",
        "tipoEstudo": "tese de doutorado — prévia",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Contexto de acesso externo, interação tutor–gato e desenho de questionários.",
        "comoUsar": "",
        "cautelas": "Arquivo PREVIEW de 20 páginas; capítulos e resultados completos não estão disponíveis; foco em caça, não FIC.",
        "arquivo": "PDF/Síndrome CIF/The Role of Human-Cat Interactions in Shaping Domestic Cat.pdf",
        "referencia": "CHUNG, Hee Jin. The Role of Human-Cat Interactions in Shaping Domestic Cat (Felis catus) Hunting Behavior. 2026. Dissertation (PhD in Animal Behavior) — University of California, Davis, 2026."
    },
    {
        "codigo": "N28",
        "titulo": "Artificial Intelligence in Veterinary Education: Preparing the Workforce for Clinical Applications in Diagnostics and Animal Health",
        "ano": "2026",
        "nucleo": "Núcleo 2",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "IA na educação veterinária",
        "tipoEstudo": "revisão narrativa",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Justificativa tecnológica e formação necessária para adoção responsável.",
        "comoUsar": "",
        "cautelas": "Revisão narrativa, ampla e não específica de felinos/FIC; evidências educacionais heterogêneas.",
        "arquivo": "PDF/Síndrome CIF/vetsci-13-00181.pdf",
        "referencia": "PÉREZ-GARCÍA, Esteban et al. Artificial Intelligence in Veterinary Education: Preparing the Workforce for Clinical Applications in Diagnostics and Animal Health. Veterinary Sciences, v. 13, n. 2, art. 181, 2026. DOI: 10.3390/vetsci13020181."
    },
    {
        "codigo": "N29",
        "titulo": "Seen but overlooked: animals as stakeholders in AI ethics discourses",
        "ano": "2026",
        "nucleo": "Núcleo 2",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Animais como stakeholders na ética de IA",
        "tipoEstudo": "artigo de perspectiva ética",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Ética e governança: bem-estar felino como requisito explícito do sistema.",
        "comoUsar": "",
        "cautelas": "Artigo normativo, não avaliação empírica; exemplos abrangem produção e animais de companhia.",
        "arquivo": "PDF/Síndrome CIF/vfaf057.pdf",
        "referencia": "GIERSBERG, Mona F. Seen but overlooked: animals as stakeholders in AI ethics discourses. Animal Frontiers, v. 16, n. 2, p. 34–40, 2026. DOI: 10.1093/af/vfaf057."
    },
    {
        "codigo": "N31",
        "titulo": "Síndrome de Pandora: aspectos psiconeuroendócrinos",
        "ano": "2019",
        "nucleo": "Núcleo 1",
        "fase": "A classificar",
        "status": "fichamento concluido",
        "grupo": "Aspectos psiconeuroendócrinos da Síndrome de Pandora",
        "tipoEstudo": "revisão narrativa",
        "procedencia": "NAO CONFIRMADO",
        "porQueLer": "Fundamentação clínica e fisiológica introdutória.",
        "comoUsar": "",
        "cautelas": "Revisão curta; algumas afirmações didáticas exigem retorno às fontes primárias; cópia de Síndrome CIF não tem texto, leitura feita na cópia legível indicada.",
        "arquivo": "PDF/Primeiras Leituras/06_Síndrome de Pandora.pdf",
        "referencia": "TEIXEIRA, Kelly Cristina; VIEIRA, Mayara Zanini; TORRES, Maria Lúcia Marcucci. Síndrome de Pandora: aspectos psiconeuroendócrinos. Revista de Educação Continuada em Medicina Veterinária e Zootecnia do CRMV-SP, v. 17, n. 1, p. 16–19, 2019. DOI: NÃO CONFIRMADO."
    },
    {
        "codigo": "67",
        "titulo": "Influência da cromoterapia sobre a aferição de pressão arterial de cães",
        "ano": "2026",
        "nucleo": "A classificar",
        "fase": "A classificar",
        "status": "arquivo obtido",
        "grupo": "Estresse ambiental e aferição de pressão arterial",
        "tipoEstudo": "estudo experimental",
        "procedencia": "confirmada na primeira página do PDF",
        "porQueLer": "Avalia a influência de condições ambientais sobre uma medida fisiológica em animais.",
        "comoUsar": "Pertinência para a tese ainda precisa ser avaliada.",
        "cautelas": "Estudo realizado com cães; não trata de felinos nem de Síndrome de Pandora.",
        "arquivo": "PDF/Síndrome CIF/12+1987+4829+-+Influência+da+cromoterapia+sobre+a+aferição+de+pressão+arterial+de+cães.pdf",
        "fichamento": "",
        "referencia": "FERNANDES, Tatiana Vasconcelos; ATHAR, Carolina Aben. Influência da cromoterapia sobre a aferição de pressão arterial de cães. PUBVET, v. 20, n. 7, e1987, p. 1–5, 2026. DOI: 10.31533/pubvet.v20n7e1987."
    },
    {
        "codigo": "68",
        "titulo": "Relatório de Estágio Curricular Supervisionado na área de Clínica Médica e Cirúrgica de Felinos Domésticos",
        "ano": "2026",
        "nucleo": "A classificar",
        "fase": "A classificar",
        "status": "arquivo obtido",
        "grupo": "Clínica médica e cirúrgica de felinos domésticos",
        "tipoEstudo": "trabalho de conclusão de curso",
        "procedencia": "confirmada nas páginas iniciais do PDF",
        "porQueLer": "Documento acadêmico sobre a prática clínica e cirúrgica com felinos domésticos.",
        "comoUsar": "Pertinência específica para a tese ainda precisa ser avaliada.",
        "cautelas": "Relatório de estágio; não é estudo primário sobre Síndrome de Pandora.",
        "arquivo": "PDF/Síndrome CIF/Relatório de Estágio - Nicoli Poliana.pdf,a.pdf",
        "fichamento": "",
        "referencia": "BATISTA, Nicoli Poliana. Relatório de Estágio Curricular Supervisionado na área de Clínica Médica e Cirúrgica de Felinos Domésticos. 2026. Trabalho de Conclusão de Curso (Graduação em Medicina Veterinária) — Centro de Ciências Rurais, Universidade Federal de Santa Catarina, Curitibanos, 2026."
    }
];
